/*------------------------------------------------------------*
 * chassiscfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "PMConfig.h"
	#include "Types.h"
	
int
ChassisConfig_LoadFile(char *File, ChassisConfig_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->SysRestartCause = IniGetUInt(ini, "ChassisConfiguration", "SysRestartCause", 0x0);

	data->PowerRestorePolicy = IniGetUInt(ini, "ChassisConfiguration", "PowerRestorePolicy", 0x2);

	data->ChassisPowerState.PowerState = IniGetUInt(ini, "ChassisConfiguration/ChassisPowerState", "PowerState", (0x2 << 5) | (0x0 << 4) | (0x0 << 3) | \
		    (0x0 << 2) | (0x0 << 1) | 0x1);
	data->ChassisPowerState.LastPowerEvent = IniGetUInt(ini, "ChassisConfiguration/ChassisPowerState", "LastPowerEvent", (0x0 << 4) | (0x0 << 3) | (0x0 << 2) | \
		(0x0 << 1) | 0x0);
	data->ChassisPowerState.MiscChassisState = IniGetUInt(ini, "ChassisConfiguration/ChassisPowerState", "MiscChassisState", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);
	data->ChassisPowerState.FPBtnEnables = IniGetUInt(ini, "ChassisConfiguration/ChassisPowerState", "FPBtnEnables", (0x1 << 7) | (0x1 << 6) | (0x1 << 5) | (0x1 << 4));

	data->ChassisCapabilities.CapabilitiesFlags = IniGetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "CapabilitiesFlags", (0x0 << 1) | 0x0);
	data->ChassisCapabilities.FRUInfoAddr = IniGetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "FRUInfoAddr", 32);
	data->ChassisCapabilities.SDRDeviceAddr = IniGetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "SDRDeviceAddr", 0x20);
	data->ChassisCapabilities.SELDeviceAddr = IniGetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "SELDeviceAddr", 0x20);
	data->ChassisCapabilities.SMDeviceAddr = IniGetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "SMDeviceAddr", 0x20);
	data->ChassisCapabilities.ChassBridgeFn = IniGetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "ChassBridgeFn", 0x20);

	data->PowerCycleInterval = IniGetUInt(ini, "ChassisConfiguration", "PowerCycleInterval", 2);

	data->OemBootOpt.Data1 = IniGetUInt(ini, "ChassisConfiguration/OemBootOpt", "Data1", 0x0);
	data->OemBootOpt.Data2 = IniGetUInt(ini, "ChassisConfiguration/OemBootOpt", "Data2", 0x0);

	data->SysPartitionScan = IniGetUInt(ini, "ChassisConfiguration", "SysPartitionScan", 0);

	data->SysRestartCauseChNum = IniGetUInt(ini, "ChassisConfiguration", "SysRestartCauseChNum", 0x0);

	IniCloseFile(ini);
	return 0;
}

int
ChassisConfig_SaveFile(char *File, ChassisConfig_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "ChassisConfiguration", "SysRestartCause", data->SysRestartCause);

	IniSetUInt(ini, "ChassisConfiguration", "PowerRestorePolicy", data->PowerRestorePolicy);

	IniSetUInt(ini, "ChassisConfiguration/ChassisPowerState", "PowerState", data->ChassisPowerState.PowerState);
	IniSetUInt(ini, "ChassisConfiguration/ChassisPowerState", "LastPowerEvent", data->ChassisPowerState.LastPowerEvent);
	IniSetUInt(ini, "ChassisConfiguration/ChassisPowerState", "MiscChassisState", data->ChassisPowerState.MiscChassisState);
	IniSetUInt(ini, "ChassisConfiguration/ChassisPowerState", "FPBtnEnables", data->ChassisPowerState.FPBtnEnables);

	IniSetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "CapabilitiesFlags", data->ChassisCapabilities.CapabilitiesFlags);
	IniSetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "FRUInfoAddr", data->ChassisCapabilities.FRUInfoAddr);
	IniSetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "SDRDeviceAddr", data->ChassisCapabilities.SDRDeviceAddr);
	IniSetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "SELDeviceAddr", data->ChassisCapabilities.SELDeviceAddr);
	IniSetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "SMDeviceAddr", data->ChassisCapabilities.SMDeviceAddr);
	IniSetUInt(ini, "ChassisConfiguration/ChassisCapabilities", "ChassBridgeFn", data->ChassisCapabilities.ChassBridgeFn);

	IniSetUInt(ini, "ChassisConfiguration", "PowerCycleInterval", data->PowerCycleInterval);

	IniSetUInt(ini, "ChassisConfiguration/OemBootOpt", "Data1", data->OemBootOpt.Data1);
	IniSetUInt(ini, "ChassisConfiguration/OemBootOpt", "Data2", data->OemBootOpt.Data2);

	IniSetUInt(ini, "ChassisConfiguration", "SysPartitionScan", data->SysPartitionScan);

	IniSetUInt(ini, "ChassisConfiguration", "SysRestartCauseChNum", data->SysRestartCauseChNum);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}


	/*End Chassis Configuration */
	