/*------------------------------------------------------------*
 * encusrpswd.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "Types.h"
	#include "IPMIConf.h"
	#include "featuredef.h"
	
int
EncUserPswd_LoadFile(char *File, BMCInfo_t *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[0].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/0", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[0].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/0", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[0].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/0", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[1].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/1", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[1].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/1", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[1].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/1", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[2].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/2", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[2].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/2", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[2].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/2", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[3].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/3", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[3].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/3", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[3].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/3", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[4].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/4", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[4].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/4", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[4].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/4", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[5].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/5", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[5].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/5", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[5].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/5", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[6].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/6", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[6].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/6", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[6].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/6", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[7].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/7", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[7].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/7", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[7].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/7", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[8].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/8", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[8].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/8", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[8].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/8", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[9].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/9", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[9].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/9", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[9].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/9", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[10].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/10", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[10].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/10", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[10].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/10", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[11].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/11", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[11].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/11", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[11].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/11", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[12].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/12", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[12].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/12", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[12].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/12", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[13].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/13", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[13].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/13", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[13].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/13", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[14].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/14", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[14].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/14", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[14].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/14", "passwdenc_len", 0);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	strncpy((char*)data->EncryptedUserInfo[15].EncryptedPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/15", "EncryptedPswd", ""), 256);
	}
	strncpy((char*)data->EncryptedUserInfo[15].EncryptedHexPswd, IniGetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/15", "EncryptedHexPswd", ""), 512);
	data->EncryptedUserInfo[15].passwdenc_len = IniGetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/15", "passwdenc_len", 0);

	IniCloseFile(ini);
	return 0;
}

int
EncUserPswd_SaveFile(char *File, BMCInfo_t *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/0", "EncryptedPswd", (char*)data->EncryptedUserInfo[0].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/0", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[0].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/0", "passwdenc_len", data->EncryptedUserInfo[0].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/1", "EncryptedPswd", (char*)data->EncryptedUserInfo[1].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/1", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[1].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/1", "passwdenc_len", data->EncryptedUserInfo[1].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/2", "EncryptedPswd", (char*)data->EncryptedUserInfo[2].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/2", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[2].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/2", "passwdenc_len", data->EncryptedUserInfo[2].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/3", "EncryptedPswd", (char*)data->EncryptedUserInfo[3].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/3", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[3].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/3", "passwdenc_len", data->EncryptedUserInfo[3].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/4", "EncryptedPswd", (char*)data->EncryptedUserInfo[4].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/4", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[4].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/4", "passwdenc_len", data->EncryptedUserInfo[4].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/5", "EncryptedPswd", (char*)data->EncryptedUserInfo[5].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/5", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[5].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/5", "passwdenc_len", data->EncryptedUserInfo[5].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/6", "EncryptedPswd", (char*)data->EncryptedUserInfo[6].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/6", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[6].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/6", "passwdenc_len", data->EncryptedUserInfo[6].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/7", "EncryptedPswd", (char*)data->EncryptedUserInfo[7].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/7", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[7].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/7", "passwdenc_len", data->EncryptedUserInfo[7].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/8", "EncryptedPswd", (char*)data->EncryptedUserInfo[8].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/8", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[8].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/8", "passwdenc_len", data->EncryptedUserInfo[8].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/9", "EncryptedPswd", (char*)data->EncryptedUserInfo[9].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/9", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[9].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/9", "passwdenc_len", data->EncryptedUserInfo[9].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/10", "EncryptedPswd", (char*)data->EncryptedUserInfo[10].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/10", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[10].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/10", "passwdenc_len", data->EncryptedUserInfo[10].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/11", "EncryptedPswd", (char*)data->EncryptedUserInfo[11].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/11", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[11].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/11", "passwdenc_len", data->EncryptedUserInfo[11].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/12", "EncryptedPswd", (char*)data->EncryptedUserInfo[12].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/12", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[12].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/12", "passwdenc_len", data->EncryptedUserInfo[12].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/13", "EncryptedPswd", (char*)data->EncryptedUserInfo[13].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/13", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[13].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/13", "passwdenc_len", data->EncryptedUserInfo[13].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/14", "EncryptedPswd", (char*)data->EncryptedUserInfo[14].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/14", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[14].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/14", "passwdenc_len", data->EncryptedUserInfo[14].passwdenc_len);
	if(g_corefeatures.backward_compatibility_userpswd_encryption == ENABLED) {
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/15", "EncryptedPswd", (char*)data->EncryptedUserInfo[15].EncryptedPswd);
	}
	IniSetStr(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/15", "EncryptedHexPswd", (char*)data->EncryptedUserInfo[15].EncryptedHexPswd);
	IniSetUInt(ini, "EncryptedUserPswdConfig/EncryptedUserInfo/15", "passwdenc_len", data->EncryptedUserInfo[15].passwdenc_len);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

