/*------------------------------------------------------------*
 * lanchannel1.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "PMConfig.h"
	#include "Types.h"
	
int
LAN1ChannelInfo_LoadFile(char *File, ChannelInfo_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->ID = IniGetUInt(ini, "LANChannel1Information", "ID", 0x43484944);

	data->ChannelIndex = IniGetUInt(ini, "LANChannel1Information", "ChannelIndex", 2);

	data->ChannelNumber = IniGetUInt(ini, "LANChannel1Information", "ChannelNumber", 0x1);

	data->ChannelType = IniGetUInt(ini, "LANChannel1Information", "ChannelType", 0x1);

	data->ChannelMedium = IniGetUInt(ini, "LANChannel1Information", "ChannelMedium", 0x4);

	data->ChannelProtocol = IniGetUInt(ini, "LANChannel1Information", "ChannelProtocol", 0x1);

	data->SessionSupport = IniGetUInt(ini, "LANChannel1Information", "SessionSupport", 0x2);

	data->ActiveSession = IniGetUInt(ini, "LANChannel1Information", "ActiveSession", 0x0);

	data->AuthType[0] = IniGetUInt(ini, "LANChannel1Information", "AuthType/0", 0);
	data->AuthType[1] = IniGetUInt(ini, "LANChannel1Information", "AuthType/1", 0);
	data->AuthType[2] = IniGetUInt(ini, "LANChannel1Information", "AuthType/2", 0);
	data->AuthType[3] = IniGetUInt(ini, "LANChannel1Information", "AuthType/3", 0);
	data->AuthType[4] = IniGetUInt(ini, "LANChannel1Information", "AuthType/4", 0);
	data->AuthType[5] = IniGetUInt(ini, "LANChannel1Information", "AuthType/5", 0);
	data->AuthType[6] = IniGetUInt(ini, "LANChannel1Information", "AuthType/6", 0);

	data->ProtocolVendorId[0] = IniGetUInt(ini, "LANChannel1Information", "ProtocolVendorId/0", (0xf21b00 & 0xFF0000) >> 16);
	data->ProtocolVendorId[1] = IniGetUInt(ini, "LANChannel1Information", "ProtocolVendorId/1", (0xf21b00 & 0xFF00) >> 8);
	data->ProtocolVendorId[2] = IniGetUInt(ini, "LANChannel1Information", "ProtocolVendorId/2", (0xf21b00 & 0xFF));

	data->AuxiliaryInfo[0] = IniGetUInt(ini, "LANChannel1Information", "AuxiliaryInfo/0", (0 & 0xFF00) >> 8);
	data->AuxiliaryInfo[1] = IniGetUInt(ini, "LANChannel1Information", "AuxiliaryInfo/1", (0 & 0xFF));

	data->ReceiveMsgQ = IniGetUInt(ini, "LANChannel1Information", "ReceiveMsgQ", 0);

	data->AccessMode = IniGetUInt(ini, "LANChannel1Information", "AccessMode", 0x2);

	data->AccessModeSupported = IniGetUInt(ini, "LANChannel1Information", "AccessModeSupported", 5);

	data->Alerting = IniGetUInt(ini, "LANChannel1Information", "Alerting", 0x0);

	data->PerMessageAuth = IniGetUInt(ini, "LANChannel1Information", "PerMessageAuth", 0x1);

	data->UserLevelAuth = IniGetUInt(ini, "LANChannel1Information", "UserLevelAuth", 0x0);

	data->MaxPrivilege = IniGetUInt(ini, "LANChannel1Information", "MaxPrivilege", 4);

	data->reserved = IniGetUInt(ini, "LANChannel1Information", "reserved", 0);

	data->SetUserAccess = IniGetUInt(ini, "LANChannel1Information", "SetUserAccess", 0x1);

	data->SetChPrivilege = IniGetUInt(ini, "LANChannel1Information", "SetChPrivilege", 0x1);

	data->SessionLimit = IniGetUInt(ini, "LANChannel1Information", "SessionLimit", 15);

	data->LoginStatusNUP = IniGetUInt(ini, "LANChannel1Information", "LoginStatusNUP", 0);

	data->LoginStatusNUNP = IniGetUInt(ini, "LANChannel1Information", "LoginStatusNUNP", 1);

	data->LoginStatusNNU = IniGetUInt(ini, "LANChannel1Information", "LoginStatusNNU", 0);

	data->MaxUser = IniGetUInt(ini, "LANChannel1Information", "MaxUser", 0);

	data->NoCurrentUser = IniGetUInt(ini, "LANChannel1Information", "NoCurrentUser", 1);

	data->NoFixedUser = IniGetUInt(ini, "LANChannel1Information", "NoFixedUser", 2);

	data->ChannelIndexRam = IniGetUInt(ini, "LANChannel1Information", "ChannelIndexRam", 0);

	data->ChannelIndexNvRam = IniGetUInt(ini, "LANChannel1Information", "ChannelIndexNvRam", 0);

	data->ChannelUserInfo[0].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "ID", (((INT32U)'U'<<24) | ((INT32U)'S'<<16) | ('E'<<8) | ('R') ));
	data->ChannelUserInfo[0].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserId", 1);
	data->ChannelUserInfo[0].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "AccessLimit", 0xf);
	data->ChannelUserInfo[0].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "LinkAuth", 0x0);
	data->ChannelUserInfo[0].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserAccessCallback", 0x1);
	data->ChannelUserInfo[0].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserAccessCBCPCallback", 0x0);
	data->ChannelUserInfo[0].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserCallbackCapabilities", 1);
	data->ChannelUserInfo[0].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CBCPNegOptions", 0);
	data->ChannelUserInfo[0].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CallBack1", 0);
	data->ChannelUserInfo[0].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CallBack2", 0);
	data->ChannelUserInfo[0].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CallBack3", 0);
	data->ChannelUserInfo[0].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "FailureAttempts", 0);
	data->ChannelUserInfo[0].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "Lock", 0);
	data->ChannelUserInfo[0].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "LockedTime", 0);
	data->ChannelUserInfo[0].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/0", 2);
	data->ChannelUserInfo[0].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/1", 0);
	data->ChannelUserInfo[0].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/2", 0);
	data->ChannelUserInfo[0].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/3", 0);
	data->ChannelUserInfo[0].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "IPMIMessaging", 0);
	data->ChannelUserInfo[1].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "ID", (((INT32U)'U'<<24) | ((INT32U)'S'<<16) | ('E'<<8) | ('R') ));
	data->ChannelUserInfo[1].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserId", 2);
	data->ChannelUserInfo[1].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "AccessLimit", 0x4);
	data->ChannelUserInfo[1].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "LinkAuth", 0x0);
	data->ChannelUserInfo[1].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserAccessCallback", 0x1);
	data->ChannelUserInfo[1].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserAccessCBCPCallback", 0x0);
	data->ChannelUserInfo[1].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserCallbackCapabilities", 1);
	data->ChannelUserInfo[1].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CBCPNegOptions", 0);
	data->ChannelUserInfo[1].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CallBack1", 0);
	data->ChannelUserInfo[1].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CallBack2", 0);
	data->ChannelUserInfo[1].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CallBack3", 0);
	data->ChannelUserInfo[1].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "FailureAttempts", 0);
	data->ChannelUserInfo[1].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "Lock", 0);
	data->ChannelUserInfo[1].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "LockedTime", 0);
	data->ChannelUserInfo[1].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/0", 2);
	data->ChannelUserInfo[1].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/1", 0);
	data->ChannelUserInfo[1].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/2", 0);
	data->ChannelUserInfo[1].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/3", 0);
	data->ChannelUserInfo[1].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "IPMIMessaging", 1);
	data->ChannelUserInfo[2].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "ID", 0);
	data->ChannelUserInfo[2].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserId", 0);
	data->ChannelUserInfo[2].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "AccessLimit", 0);
	data->ChannelUserInfo[2].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "LinkAuth", 0);
	data->ChannelUserInfo[2].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserAccessCallback", 0);
	data->ChannelUserInfo[2].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[2].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[2].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CBCPNegOptions", 0);
	data->ChannelUserInfo[2].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CallBack1", 0);
	data->ChannelUserInfo[2].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CallBack2", 0);
	data->ChannelUserInfo[2].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CallBack3", 0);
	data->ChannelUserInfo[2].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "FailureAttempts", 0);
	data->ChannelUserInfo[2].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "Lock", 0);
	data->ChannelUserInfo[2].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "LockedTime", 0);
	data->ChannelUserInfo[2].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/0", 0);
	data->ChannelUserInfo[2].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/1", 0);
	data->ChannelUserInfo[2].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/2", 0);
	data->ChannelUserInfo[2].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/3", 0);
	data->ChannelUserInfo[2].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "IPMIMessaging", 0);
	data->ChannelUserInfo[3].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "ID", 0);
	data->ChannelUserInfo[3].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserId", 0);
	data->ChannelUserInfo[3].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "AccessLimit", 0);
	data->ChannelUserInfo[3].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "LinkAuth", 0);
	data->ChannelUserInfo[3].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserAccessCallback", 0);
	data->ChannelUserInfo[3].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[3].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[3].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CBCPNegOptions", 0);
	data->ChannelUserInfo[3].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CallBack1", 0);
	data->ChannelUserInfo[3].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CallBack2", 0);
	data->ChannelUserInfo[3].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CallBack3", 0);
	data->ChannelUserInfo[3].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "FailureAttempts", 0);
	data->ChannelUserInfo[3].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "Lock", 0);
	data->ChannelUserInfo[3].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "LockedTime", 0);
	data->ChannelUserInfo[3].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/0", 0);
	data->ChannelUserInfo[3].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/1", 0);
	data->ChannelUserInfo[3].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/2", 0);
	data->ChannelUserInfo[3].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/3", 0);
	data->ChannelUserInfo[3].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "IPMIMessaging", 0);
	data->ChannelUserInfo[4].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "ID", 0);
	data->ChannelUserInfo[4].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserId", 0);
	data->ChannelUserInfo[4].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "AccessLimit", 0);
	data->ChannelUserInfo[4].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "LinkAuth", 0);
	data->ChannelUserInfo[4].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserAccessCallback", 0);
	data->ChannelUserInfo[4].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[4].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[4].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CBCPNegOptions", 0);
	data->ChannelUserInfo[4].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CallBack1", 0);
	data->ChannelUserInfo[4].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CallBack2", 0);
	data->ChannelUserInfo[4].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CallBack3", 0);
	data->ChannelUserInfo[4].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "FailureAttempts", 0);
	data->ChannelUserInfo[4].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "Lock", 0);
	data->ChannelUserInfo[4].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "LockedTime", 0);
	data->ChannelUserInfo[4].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/0", 0);
	data->ChannelUserInfo[4].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/1", 0);
	data->ChannelUserInfo[4].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/2", 0);
	data->ChannelUserInfo[4].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/3", 0);
	data->ChannelUserInfo[4].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "IPMIMessaging", 0);
	data->ChannelUserInfo[5].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "ID", 0);
	data->ChannelUserInfo[5].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserId", 0);
	data->ChannelUserInfo[5].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "AccessLimit", 0);
	data->ChannelUserInfo[5].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "LinkAuth", 0);
	data->ChannelUserInfo[5].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserAccessCallback", 0);
	data->ChannelUserInfo[5].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[5].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[5].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CBCPNegOptions", 0);
	data->ChannelUserInfo[5].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CallBack1", 0);
	data->ChannelUserInfo[5].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CallBack2", 0);
	data->ChannelUserInfo[5].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CallBack3", 0);
	data->ChannelUserInfo[5].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "FailureAttempts", 0);
	data->ChannelUserInfo[5].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "Lock", 0);
	data->ChannelUserInfo[5].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "LockedTime", 0);
	data->ChannelUserInfo[5].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/0", 0);
	data->ChannelUserInfo[5].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/1", 0);
	data->ChannelUserInfo[5].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/2", 0);
	data->ChannelUserInfo[5].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/3", 0);
	data->ChannelUserInfo[5].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "IPMIMessaging", 0);
	data->ChannelUserInfo[6].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "ID", 0);
	data->ChannelUserInfo[6].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserId", 0);
	data->ChannelUserInfo[6].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "AccessLimit", 0);
	data->ChannelUserInfo[6].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "LinkAuth", 0);
	data->ChannelUserInfo[6].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserAccessCallback", 0);
	data->ChannelUserInfo[6].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[6].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[6].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CBCPNegOptions", 0);
	data->ChannelUserInfo[6].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CallBack1", 0);
	data->ChannelUserInfo[6].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CallBack2", 0);
	data->ChannelUserInfo[6].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CallBack3", 0);
	data->ChannelUserInfo[6].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "FailureAttempts", 0);
	data->ChannelUserInfo[6].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "Lock", 0);
	data->ChannelUserInfo[6].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "LockedTime", 0);
	data->ChannelUserInfo[6].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/0", 0);
	data->ChannelUserInfo[6].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/1", 0);
	data->ChannelUserInfo[6].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/2", 0);
	data->ChannelUserInfo[6].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/3", 0);
	data->ChannelUserInfo[6].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "IPMIMessaging", 0);
	data->ChannelUserInfo[7].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "ID", 0);
	data->ChannelUserInfo[7].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserId", 0);
	data->ChannelUserInfo[7].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "AccessLimit", 0);
	data->ChannelUserInfo[7].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "LinkAuth", 0);
	data->ChannelUserInfo[7].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserAccessCallback", 0);
	data->ChannelUserInfo[7].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[7].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[7].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CBCPNegOptions", 0);
	data->ChannelUserInfo[7].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CallBack1", 0);
	data->ChannelUserInfo[7].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CallBack2", 0);
	data->ChannelUserInfo[7].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CallBack3", 0);
	data->ChannelUserInfo[7].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "FailureAttempts", 0);
	data->ChannelUserInfo[7].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "Lock", 0);
	data->ChannelUserInfo[7].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "LockedTime", 0);
	data->ChannelUserInfo[7].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/0", 0);
	data->ChannelUserInfo[7].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/1", 0);
	data->ChannelUserInfo[7].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/2", 0);
	data->ChannelUserInfo[7].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/3", 0);
	data->ChannelUserInfo[7].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "IPMIMessaging", 0);
	data->ChannelUserInfo[8].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "ID", 0);
	data->ChannelUserInfo[8].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserId", 0);
	data->ChannelUserInfo[8].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "AccessLimit", 0);
	data->ChannelUserInfo[8].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "LinkAuth", 0);
	data->ChannelUserInfo[8].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserAccessCallback", 0);
	data->ChannelUserInfo[8].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[8].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[8].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CBCPNegOptions", 0);
	data->ChannelUserInfo[8].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CallBack1", 0);
	data->ChannelUserInfo[8].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CallBack2", 0);
	data->ChannelUserInfo[8].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CallBack3", 0);
	data->ChannelUserInfo[8].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "FailureAttempts", 0);
	data->ChannelUserInfo[8].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "Lock", 0);
	data->ChannelUserInfo[8].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "LockedTime", 0);
	data->ChannelUserInfo[8].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/0", 0);
	data->ChannelUserInfo[8].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/1", 0);
	data->ChannelUserInfo[8].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/2", 0);
	data->ChannelUserInfo[8].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/3", 0);
	data->ChannelUserInfo[8].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "IPMIMessaging", 0);
	data->ChannelUserInfo[9].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "ID", 0);
	data->ChannelUserInfo[9].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserId", 0);
	data->ChannelUserInfo[9].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "AccessLimit", 0);
	data->ChannelUserInfo[9].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "LinkAuth", 0);
	data->ChannelUserInfo[9].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserAccessCallback", 0);
	data->ChannelUserInfo[9].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[9].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[9].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CBCPNegOptions", 0);
	data->ChannelUserInfo[9].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CallBack1", 0);
	data->ChannelUserInfo[9].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CallBack2", 0);
	data->ChannelUserInfo[9].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CallBack3", 0);
	data->ChannelUserInfo[9].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "FailureAttempts", 0);
	data->ChannelUserInfo[9].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "Lock", 0);
	data->ChannelUserInfo[9].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "LockedTime", 0);
	data->ChannelUserInfo[9].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/0", 0);
	data->ChannelUserInfo[9].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/1", 0);
	data->ChannelUserInfo[9].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/2", 0);
	data->ChannelUserInfo[9].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/3", 0);
	data->ChannelUserInfo[9].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "IPMIMessaging", 0);
	data->ChannelUserInfo[10].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "ID", 0);
	data->ChannelUserInfo[10].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserId", 0);
	data->ChannelUserInfo[10].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "AccessLimit", 0);
	data->ChannelUserInfo[10].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "LinkAuth", 0);
	data->ChannelUserInfo[10].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserAccessCallback", 0);
	data->ChannelUserInfo[10].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[10].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[10].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CBCPNegOptions", 0);
	data->ChannelUserInfo[10].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CallBack1", 0);
	data->ChannelUserInfo[10].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CallBack2", 0);
	data->ChannelUserInfo[10].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CallBack3", 0);
	data->ChannelUserInfo[10].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "FailureAttempts", 0);
	data->ChannelUserInfo[10].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "Lock", 0);
	data->ChannelUserInfo[10].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "LockedTime", 0);
	data->ChannelUserInfo[10].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/0", 0);
	data->ChannelUserInfo[10].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/1", 0);
	data->ChannelUserInfo[10].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/2", 0);
	data->ChannelUserInfo[10].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/3", 0);
	data->ChannelUserInfo[10].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "IPMIMessaging", 0);
	data->ChannelUserInfo[11].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "ID", 0);
	data->ChannelUserInfo[11].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserId", 0);
	data->ChannelUserInfo[11].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "AccessLimit", 0);
	data->ChannelUserInfo[11].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "LinkAuth", 0);
	data->ChannelUserInfo[11].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserAccessCallback", 0);
	data->ChannelUserInfo[11].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[11].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[11].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CBCPNegOptions", 0);
	data->ChannelUserInfo[11].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CallBack1", 0);
	data->ChannelUserInfo[11].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CallBack2", 0);
	data->ChannelUserInfo[11].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CallBack3", 0);
	data->ChannelUserInfo[11].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "FailureAttempts", 0);
	data->ChannelUserInfo[11].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "Lock", 0);
	data->ChannelUserInfo[11].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "LockedTime", 0);
	data->ChannelUserInfo[11].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/0", 0);
	data->ChannelUserInfo[11].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/1", 0);
	data->ChannelUserInfo[11].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/2", 0);
	data->ChannelUserInfo[11].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/3", 0);
	data->ChannelUserInfo[11].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "IPMIMessaging", 0);
	data->ChannelUserInfo[12].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "ID", 0);
	data->ChannelUserInfo[12].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserId", 0);
	data->ChannelUserInfo[12].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "AccessLimit", 0);
	data->ChannelUserInfo[12].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "LinkAuth", 0);
	data->ChannelUserInfo[12].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserAccessCallback", 0);
	data->ChannelUserInfo[12].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[12].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[12].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CBCPNegOptions", 0);
	data->ChannelUserInfo[12].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CallBack1", 0);
	data->ChannelUserInfo[12].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CallBack2", 0);
	data->ChannelUserInfo[12].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CallBack3", 0);
	data->ChannelUserInfo[12].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "FailureAttempts", 0);
	data->ChannelUserInfo[12].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "Lock", 0);
	data->ChannelUserInfo[12].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "LockedTime", 0);
	data->ChannelUserInfo[12].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/0", 0);
	data->ChannelUserInfo[12].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/1", 0);
	data->ChannelUserInfo[12].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/2", 0);
	data->ChannelUserInfo[12].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/3", 0);
	data->ChannelUserInfo[12].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "IPMIMessaging", 0);
	data->ChannelUserInfo[13].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "ID", 0);
	data->ChannelUserInfo[13].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserId", 0);
	data->ChannelUserInfo[13].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "AccessLimit", 0);
	data->ChannelUserInfo[13].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "LinkAuth", 0);
	data->ChannelUserInfo[13].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserAccessCallback", 0);
	data->ChannelUserInfo[13].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[13].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[13].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CBCPNegOptions", 0);
	data->ChannelUserInfo[13].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CallBack1", 0);
	data->ChannelUserInfo[13].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CallBack2", 0);
	data->ChannelUserInfo[13].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CallBack3", 0);
	data->ChannelUserInfo[13].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "FailureAttempts", 0);
	data->ChannelUserInfo[13].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "Lock", 0);
	data->ChannelUserInfo[13].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "LockedTime", 0);
	data->ChannelUserInfo[13].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/0", 0);
	data->ChannelUserInfo[13].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/1", 0);
	data->ChannelUserInfo[13].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/2", 0);
	data->ChannelUserInfo[13].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/3", 0);
	data->ChannelUserInfo[13].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "IPMIMessaging", 0);
	data->ChannelUserInfo[14].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "ID", 0);
	data->ChannelUserInfo[14].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserId", 0);
	data->ChannelUserInfo[14].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "AccessLimit", 0);
	data->ChannelUserInfo[14].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "LinkAuth", 0);
	data->ChannelUserInfo[14].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserAccessCallback", 0);
	data->ChannelUserInfo[14].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[14].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[14].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CBCPNegOptions", 0);
	data->ChannelUserInfo[14].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CallBack1", 0);
	data->ChannelUserInfo[14].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CallBack2", 0);
	data->ChannelUserInfo[14].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CallBack3", 0);
	data->ChannelUserInfo[14].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "FailureAttempts", 0);
	data->ChannelUserInfo[14].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "Lock", 0);
	data->ChannelUserInfo[14].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "LockedTime", 0);
	data->ChannelUserInfo[14].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/0", 0);
	data->ChannelUserInfo[14].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/1", 0);
	data->ChannelUserInfo[14].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/2", 0);
	data->ChannelUserInfo[14].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/3", 0);
	data->ChannelUserInfo[14].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "IPMIMessaging", 0);
	data->ChannelUserInfo[15].ID = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "ID", 0);
	data->ChannelUserInfo[15].UserId = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserId", 0);
	data->ChannelUserInfo[15].AccessLimit = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "AccessLimit", 0);
	data->ChannelUserInfo[15].LinkAuth = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "LinkAuth", 0);
	data->ChannelUserInfo[15].UserAccessCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserAccessCallback", 0);
	data->ChannelUserInfo[15].UserAccessCBCPCallback = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[15].UserCallbackCapabilities = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[15].CBCPNegOptions = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CBCPNegOptions", 0);
	data->ChannelUserInfo[15].CallBack1 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CallBack1", 0);
	data->ChannelUserInfo[15].CallBack2 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CallBack2", 0);
	data->ChannelUserInfo[15].CallBack3 = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CallBack3", 0);
	data->ChannelUserInfo[15].FailureAttempts = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "FailureAttempts", 0);
	data->ChannelUserInfo[15].Lock = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "Lock", 0);
	data->ChannelUserInfo[15].LockedTime = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "LockedTime", 0);
	data->ChannelUserInfo[15].PayloadEnables[0] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/0", 0);
	data->ChannelUserInfo[15].PayloadEnables[1] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/1", 0);
	data->ChannelUserInfo[15].PayloadEnables[2] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/2", 0);
	data->ChannelUserInfo[15].PayloadEnables[3] = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/3", 0);
	data->ChannelUserInfo[15].IPMIMessaging = IniGetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "IPMIMessaging", 0);

	IniCloseFile(ini);
	return 0;
}

int
LAN1ChannelInfo_SaveFile(char *File, ChannelInfo_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "LANChannel1Information", "ID", data->ID);

	IniSetUInt(ini, "LANChannel1Information", "ChannelIndex", data->ChannelIndex);

	IniSetUInt(ini, "LANChannel1Information", "ChannelNumber", data->ChannelNumber);

	IniSetUInt(ini, "LANChannel1Information", "ChannelType", data->ChannelType);

	IniSetUInt(ini, "LANChannel1Information", "ChannelMedium", data->ChannelMedium);

	IniSetUInt(ini, "LANChannel1Information", "ChannelProtocol", data->ChannelProtocol);

	IniSetUInt(ini, "LANChannel1Information", "SessionSupport", data->SessionSupport);

	IniSetUInt(ini, "LANChannel1Information", "ActiveSession", data->ActiveSession);

	IniSetUInt(ini, "LANChannel1Information", "AuthType/0", data->AuthType[0]);
	IniSetUInt(ini, "LANChannel1Information", "AuthType/1", data->AuthType[1]);
	IniSetUInt(ini, "LANChannel1Information", "AuthType/2", data->AuthType[2]);
	IniSetUInt(ini, "LANChannel1Information", "AuthType/3", data->AuthType[3]);
	IniSetUInt(ini, "LANChannel1Information", "AuthType/4", data->AuthType[4]);
	IniSetUInt(ini, "LANChannel1Information", "AuthType/5", data->AuthType[5]);
	IniSetUInt(ini, "LANChannel1Information", "AuthType/6", data->AuthType[6]);

	IniSetUInt(ini, "LANChannel1Information", "ProtocolVendorId/0", data->ProtocolVendorId[0]);
	IniSetUInt(ini, "LANChannel1Information", "ProtocolVendorId/1", data->ProtocolVendorId[1]);
	IniSetUInt(ini, "LANChannel1Information", "ProtocolVendorId/2", data->ProtocolVendorId[2]);

	IniSetUInt(ini, "LANChannel1Information", "AuxiliaryInfo/0", data->AuxiliaryInfo[0]);
	IniSetUInt(ini, "LANChannel1Information", "AuxiliaryInfo/1", data->AuxiliaryInfo[1]);

	IniSetUInt(ini, "LANChannel1Information", "ReceiveMsgQ", data->ReceiveMsgQ);

	IniSetUInt(ini, "LANChannel1Information", "AccessMode", data->AccessMode);

	IniSetUInt(ini, "LANChannel1Information", "AccessModeSupported", data->AccessModeSupported);

	IniSetUInt(ini, "LANChannel1Information", "Alerting", data->Alerting);

	IniSetUInt(ini, "LANChannel1Information", "PerMessageAuth", data->PerMessageAuth);

	IniSetUInt(ini, "LANChannel1Information", "UserLevelAuth", data->UserLevelAuth);

	IniSetUInt(ini, "LANChannel1Information", "MaxPrivilege", data->MaxPrivilege);

	IniSetUInt(ini, "LANChannel1Information", "reserved", data->reserved);

	IniSetUInt(ini, "LANChannel1Information", "SetUserAccess", data->SetUserAccess);

	IniSetUInt(ini, "LANChannel1Information", "SetChPrivilege", data->SetChPrivilege);

	IniSetUInt(ini, "LANChannel1Information", "SessionLimit", data->SessionLimit);

	IniSetUInt(ini, "LANChannel1Information", "LoginStatusNUP", data->LoginStatusNUP);

	IniSetUInt(ini, "LANChannel1Information", "LoginStatusNUNP", data->LoginStatusNUNP);

	IniSetUInt(ini, "LANChannel1Information", "LoginStatusNNU", data->LoginStatusNNU);

	IniSetUInt(ini, "LANChannel1Information", "MaxUser", data->MaxUser);

	IniSetUInt(ini, "LANChannel1Information", "NoCurrentUser", data->NoCurrentUser);

	IniSetUInt(ini, "LANChannel1Information", "NoFixedUser", data->NoFixedUser);

	IniSetUInt(ini, "LANChannel1Information", "ChannelIndexRam", data->ChannelIndexRam);

	IniSetUInt(ini, "LANChannel1Information", "ChannelIndexNvRam", data->ChannelIndexNvRam);

	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "ID", data->ChannelUserInfo[0].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserId", data->ChannelUserInfo[0].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "AccessLimit", data->ChannelUserInfo[0].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "LinkAuth", data->ChannelUserInfo[0].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserAccessCallback", data->ChannelUserInfo[0].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserAccessCBCPCallback", data->ChannelUserInfo[0].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "UserCallbackCapabilities", data->ChannelUserInfo[0].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CBCPNegOptions", data->ChannelUserInfo[0].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CallBack1", data->ChannelUserInfo[0].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CallBack2", data->ChannelUserInfo[0].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "CallBack3", data->ChannelUserInfo[0].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "FailureAttempts", data->ChannelUserInfo[0].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "Lock", data->ChannelUserInfo[0].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "LockedTime", data->ChannelUserInfo[0].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/0", data->ChannelUserInfo[0].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/1", data->ChannelUserInfo[0].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/2", data->ChannelUserInfo[0].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "PayloadEnables/3", data->ChannelUserInfo[0].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/0", "IPMIMessaging", data->ChannelUserInfo[0].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "ID", data->ChannelUserInfo[1].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserId", data->ChannelUserInfo[1].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "AccessLimit", data->ChannelUserInfo[1].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "LinkAuth", data->ChannelUserInfo[1].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserAccessCallback", data->ChannelUserInfo[1].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserAccessCBCPCallback", data->ChannelUserInfo[1].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "UserCallbackCapabilities", data->ChannelUserInfo[1].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CBCPNegOptions", data->ChannelUserInfo[1].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CallBack1", data->ChannelUserInfo[1].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CallBack2", data->ChannelUserInfo[1].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "CallBack3", data->ChannelUserInfo[1].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "FailureAttempts", data->ChannelUserInfo[1].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "Lock", data->ChannelUserInfo[1].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "LockedTime", data->ChannelUserInfo[1].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/0", data->ChannelUserInfo[1].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/1", data->ChannelUserInfo[1].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/2", data->ChannelUserInfo[1].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "PayloadEnables/3", data->ChannelUserInfo[1].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/1", "IPMIMessaging", data->ChannelUserInfo[1].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "ID", data->ChannelUserInfo[2].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserId", data->ChannelUserInfo[2].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "AccessLimit", data->ChannelUserInfo[2].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "LinkAuth", data->ChannelUserInfo[2].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserAccessCallback", data->ChannelUserInfo[2].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserAccessCBCPCallback", data->ChannelUserInfo[2].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "UserCallbackCapabilities", data->ChannelUserInfo[2].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CBCPNegOptions", data->ChannelUserInfo[2].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CallBack1", data->ChannelUserInfo[2].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CallBack2", data->ChannelUserInfo[2].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "CallBack3", data->ChannelUserInfo[2].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "FailureAttempts", data->ChannelUserInfo[2].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "Lock", data->ChannelUserInfo[2].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "LockedTime", data->ChannelUserInfo[2].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/0", data->ChannelUserInfo[2].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/1", data->ChannelUserInfo[2].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/2", data->ChannelUserInfo[2].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "PayloadEnables/3", data->ChannelUserInfo[2].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/2", "IPMIMessaging", data->ChannelUserInfo[2].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "ID", data->ChannelUserInfo[3].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserId", data->ChannelUserInfo[3].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "AccessLimit", data->ChannelUserInfo[3].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "LinkAuth", data->ChannelUserInfo[3].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserAccessCallback", data->ChannelUserInfo[3].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserAccessCBCPCallback", data->ChannelUserInfo[3].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "UserCallbackCapabilities", data->ChannelUserInfo[3].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CBCPNegOptions", data->ChannelUserInfo[3].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CallBack1", data->ChannelUserInfo[3].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CallBack2", data->ChannelUserInfo[3].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "CallBack3", data->ChannelUserInfo[3].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "FailureAttempts", data->ChannelUserInfo[3].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "Lock", data->ChannelUserInfo[3].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "LockedTime", data->ChannelUserInfo[3].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/0", data->ChannelUserInfo[3].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/1", data->ChannelUserInfo[3].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/2", data->ChannelUserInfo[3].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "PayloadEnables/3", data->ChannelUserInfo[3].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/3", "IPMIMessaging", data->ChannelUserInfo[3].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "ID", data->ChannelUserInfo[4].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserId", data->ChannelUserInfo[4].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "AccessLimit", data->ChannelUserInfo[4].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "LinkAuth", data->ChannelUserInfo[4].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserAccessCallback", data->ChannelUserInfo[4].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserAccessCBCPCallback", data->ChannelUserInfo[4].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "UserCallbackCapabilities", data->ChannelUserInfo[4].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CBCPNegOptions", data->ChannelUserInfo[4].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CallBack1", data->ChannelUserInfo[4].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CallBack2", data->ChannelUserInfo[4].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "CallBack3", data->ChannelUserInfo[4].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "FailureAttempts", data->ChannelUserInfo[4].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "Lock", data->ChannelUserInfo[4].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "LockedTime", data->ChannelUserInfo[4].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/0", data->ChannelUserInfo[4].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/1", data->ChannelUserInfo[4].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/2", data->ChannelUserInfo[4].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "PayloadEnables/3", data->ChannelUserInfo[4].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/4", "IPMIMessaging", data->ChannelUserInfo[4].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "ID", data->ChannelUserInfo[5].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserId", data->ChannelUserInfo[5].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "AccessLimit", data->ChannelUserInfo[5].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "LinkAuth", data->ChannelUserInfo[5].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserAccessCallback", data->ChannelUserInfo[5].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserAccessCBCPCallback", data->ChannelUserInfo[5].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "UserCallbackCapabilities", data->ChannelUserInfo[5].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CBCPNegOptions", data->ChannelUserInfo[5].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CallBack1", data->ChannelUserInfo[5].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CallBack2", data->ChannelUserInfo[5].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "CallBack3", data->ChannelUserInfo[5].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "FailureAttempts", data->ChannelUserInfo[5].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "Lock", data->ChannelUserInfo[5].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "LockedTime", data->ChannelUserInfo[5].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/0", data->ChannelUserInfo[5].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/1", data->ChannelUserInfo[5].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/2", data->ChannelUserInfo[5].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "PayloadEnables/3", data->ChannelUserInfo[5].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/5", "IPMIMessaging", data->ChannelUserInfo[5].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "ID", data->ChannelUserInfo[6].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserId", data->ChannelUserInfo[6].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "AccessLimit", data->ChannelUserInfo[6].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "LinkAuth", data->ChannelUserInfo[6].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserAccessCallback", data->ChannelUserInfo[6].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserAccessCBCPCallback", data->ChannelUserInfo[6].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "UserCallbackCapabilities", data->ChannelUserInfo[6].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CBCPNegOptions", data->ChannelUserInfo[6].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CallBack1", data->ChannelUserInfo[6].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CallBack2", data->ChannelUserInfo[6].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "CallBack3", data->ChannelUserInfo[6].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "FailureAttempts", data->ChannelUserInfo[6].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "Lock", data->ChannelUserInfo[6].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "LockedTime", data->ChannelUserInfo[6].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/0", data->ChannelUserInfo[6].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/1", data->ChannelUserInfo[6].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/2", data->ChannelUserInfo[6].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "PayloadEnables/3", data->ChannelUserInfo[6].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/6", "IPMIMessaging", data->ChannelUserInfo[6].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "ID", data->ChannelUserInfo[7].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserId", data->ChannelUserInfo[7].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "AccessLimit", data->ChannelUserInfo[7].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "LinkAuth", data->ChannelUserInfo[7].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserAccessCallback", data->ChannelUserInfo[7].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserAccessCBCPCallback", data->ChannelUserInfo[7].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "UserCallbackCapabilities", data->ChannelUserInfo[7].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CBCPNegOptions", data->ChannelUserInfo[7].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CallBack1", data->ChannelUserInfo[7].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CallBack2", data->ChannelUserInfo[7].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "CallBack3", data->ChannelUserInfo[7].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "FailureAttempts", data->ChannelUserInfo[7].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "Lock", data->ChannelUserInfo[7].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "LockedTime", data->ChannelUserInfo[7].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/0", data->ChannelUserInfo[7].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/1", data->ChannelUserInfo[7].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/2", data->ChannelUserInfo[7].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "PayloadEnables/3", data->ChannelUserInfo[7].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/7", "IPMIMessaging", data->ChannelUserInfo[7].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "ID", data->ChannelUserInfo[8].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserId", data->ChannelUserInfo[8].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "AccessLimit", data->ChannelUserInfo[8].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "LinkAuth", data->ChannelUserInfo[8].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserAccessCallback", data->ChannelUserInfo[8].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserAccessCBCPCallback", data->ChannelUserInfo[8].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "UserCallbackCapabilities", data->ChannelUserInfo[8].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CBCPNegOptions", data->ChannelUserInfo[8].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CallBack1", data->ChannelUserInfo[8].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CallBack2", data->ChannelUserInfo[8].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "CallBack3", data->ChannelUserInfo[8].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "FailureAttempts", data->ChannelUserInfo[8].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "Lock", data->ChannelUserInfo[8].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "LockedTime", data->ChannelUserInfo[8].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/0", data->ChannelUserInfo[8].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/1", data->ChannelUserInfo[8].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/2", data->ChannelUserInfo[8].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "PayloadEnables/3", data->ChannelUserInfo[8].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/8", "IPMIMessaging", data->ChannelUserInfo[8].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "ID", data->ChannelUserInfo[9].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserId", data->ChannelUserInfo[9].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "AccessLimit", data->ChannelUserInfo[9].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "LinkAuth", data->ChannelUserInfo[9].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserAccessCallback", data->ChannelUserInfo[9].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserAccessCBCPCallback", data->ChannelUserInfo[9].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "UserCallbackCapabilities", data->ChannelUserInfo[9].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CBCPNegOptions", data->ChannelUserInfo[9].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CallBack1", data->ChannelUserInfo[9].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CallBack2", data->ChannelUserInfo[9].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "CallBack3", data->ChannelUserInfo[9].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "FailureAttempts", data->ChannelUserInfo[9].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "Lock", data->ChannelUserInfo[9].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "LockedTime", data->ChannelUserInfo[9].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/0", data->ChannelUserInfo[9].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/1", data->ChannelUserInfo[9].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/2", data->ChannelUserInfo[9].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "PayloadEnables/3", data->ChannelUserInfo[9].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/9", "IPMIMessaging", data->ChannelUserInfo[9].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "ID", data->ChannelUserInfo[10].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserId", data->ChannelUserInfo[10].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "AccessLimit", data->ChannelUserInfo[10].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "LinkAuth", data->ChannelUserInfo[10].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserAccessCallback", data->ChannelUserInfo[10].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserAccessCBCPCallback", data->ChannelUserInfo[10].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "UserCallbackCapabilities", data->ChannelUserInfo[10].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CBCPNegOptions", data->ChannelUserInfo[10].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CallBack1", data->ChannelUserInfo[10].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CallBack2", data->ChannelUserInfo[10].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "CallBack3", data->ChannelUserInfo[10].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "FailureAttempts", data->ChannelUserInfo[10].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "Lock", data->ChannelUserInfo[10].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "LockedTime", data->ChannelUserInfo[10].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/0", data->ChannelUserInfo[10].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/1", data->ChannelUserInfo[10].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/2", data->ChannelUserInfo[10].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "PayloadEnables/3", data->ChannelUserInfo[10].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/10", "IPMIMessaging", data->ChannelUserInfo[10].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "ID", data->ChannelUserInfo[11].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserId", data->ChannelUserInfo[11].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "AccessLimit", data->ChannelUserInfo[11].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "LinkAuth", data->ChannelUserInfo[11].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserAccessCallback", data->ChannelUserInfo[11].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserAccessCBCPCallback", data->ChannelUserInfo[11].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "UserCallbackCapabilities", data->ChannelUserInfo[11].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CBCPNegOptions", data->ChannelUserInfo[11].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CallBack1", data->ChannelUserInfo[11].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CallBack2", data->ChannelUserInfo[11].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "CallBack3", data->ChannelUserInfo[11].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "FailureAttempts", data->ChannelUserInfo[11].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "Lock", data->ChannelUserInfo[11].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "LockedTime", data->ChannelUserInfo[11].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/0", data->ChannelUserInfo[11].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/1", data->ChannelUserInfo[11].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/2", data->ChannelUserInfo[11].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "PayloadEnables/3", data->ChannelUserInfo[11].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/11", "IPMIMessaging", data->ChannelUserInfo[11].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "ID", data->ChannelUserInfo[12].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserId", data->ChannelUserInfo[12].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "AccessLimit", data->ChannelUserInfo[12].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "LinkAuth", data->ChannelUserInfo[12].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserAccessCallback", data->ChannelUserInfo[12].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserAccessCBCPCallback", data->ChannelUserInfo[12].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "UserCallbackCapabilities", data->ChannelUserInfo[12].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CBCPNegOptions", data->ChannelUserInfo[12].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CallBack1", data->ChannelUserInfo[12].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CallBack2", data->ChannelUserInfo[12].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "CallBack3", data->ChannelUserInfo[12].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "FailureAttempts", data->ChannelUserInfo[12].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "Lock", data->ChannelUserInfo[12].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "LockedTime", data->ChannelUserInfo[12].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/0", data->ChannelUserInfo[12].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/1", data->ChannelUserInfo[12].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/2", data->ChannelUserInfo[12].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "PayloadEnables/3", data->ChannelUserInfo[12].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/12", "IPMIMessaging", data->ChannelUserInfo[12].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "ID", data->ChannelUserInfo[13].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserId", data->ChannelUserInfo[13].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "AccessLimit", data->ChannelUserInfo[13].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "LinkAuth", data->ChannelUserInfo[13].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserAccessCallback", data->ChannelUserInfo[13].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserAccessCBCPCallback", data->ChannelUserInfo[13].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "UserCallbackCapabilities", data->ChannelUserInfo[13].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CBCPNegOptions", data->ChannelUserInfo[13].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CallBack1", data->ChannelUserInfo[13].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CallBack2", data->ChannelUserInfo[13].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "CallBack3", data->ChannelUserInfo[13].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "FailureAttempts", data->ChannelUserInfo[13].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "Lock", data->ChannelUserInfo[13].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "LockedTime", data->ChannelUserInfo[13].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/0", data->ChannelUserInfo[13].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/1", data->ChannelUserInfo[13].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/2", data->ChannelUserInfo[13].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "PayloadEnables/3", data->ChannelUserInfo[13].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/13", "IPMIMessaging", data->ChannelUserInfo[13].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "ID", data->ChannelUserInfo[14].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserId", data->ChannelUserInfo[14].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "AccessLimit", data->ChannelUserInfo[14].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "LinkAuth", data->ChannelUserInfo[14].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserAccessCallback", data->ChannelUserInfo[14].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserAccessCBCPCallback", data->ChannelUserInfo[14].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "UserCallbackCapabilities", data->ChannelUserInfo[14].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CBCPNegOptions", data->ChannelUserInfo[14].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CallBack1", data->ChannelUserInfo[14].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CallBack2", data->ChannelUserInfo[14].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "CallBack3", data->ChannelUserInfo[14].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "FailureAttempts", data->ChannelUserInfo[14].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "Lock", data->ChannelUserInfo[14].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "LockedTime", data->ChannelUserInfo[14].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/0", data->ChannelUserInfo[14].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/1", data->ChannelUserInfo[14].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/2", data->ChannelUserInfo[14].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "PayloadEnables/3", data->ChannelUserInfo[14].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/14", "IPMIMessaging", data->ChannelUserInfo[14].IPMIMessaging);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "ID", data->ChannelUserInfo[15].ID);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserId", data->ChannelUserInfo[15].UserId);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "AccessLimit", data->ChannelUserInfo[15].AccessLimit);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "LinkAuth", data->ChannelUserInfo[15].LinkAuth);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserAccessCallback", data->ChannelUserInfo[15].UserAccessCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserAccessCBCPCallback", data->ChannelUserInfo[15].UserAccessCBCPCallback);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "UserCallbackCapabilities", data->ChannelUserInfo[15].UserCallbackCapabilities);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CBCPNegOptions", data->ChannelUserInfo[15].CBCPNegOptions);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CallBack1", data->ChannelUserInfo[15].CallBack1);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CallBack2", data->ChannelUserInfo[15].CallBack2);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "CallBack3", data->ChannelUserInfo[15].CallBack3);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "FailureAttempts", data->ChannelUserInfo[15].FailureAttempts);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "Lock", data->ChannelUserInfo[15].Lock);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "LockedTime", data->ChannelUserInfo[15].LockedTime);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/0", data->ChannelUserInfo[15].PayloadEnables[0]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/1", data->ChannelUserInfo[15].PayloadEnables[1]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/2", data->ChannelUserInfo[15].PayloadEnables[2]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "PayloadEnables/3", data->ChannelUserInfo[15].PayloadEnables[3]);
	IniSetUInt(ini, "LANChannel1Information/ChannelUserInfo/15", "IPMIMessaging", data->ChannelUserInfo[15].IPMIMessaging);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}


	 /* End of LAN Channel 1 information */
	