/*------------------------------------------------------------*
 * lankcscfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

        #include "Types.h"
        #include "IPMIConf.h"
        #include "LANConfig.h"
        
int
LANKCSConfig_LoadFile(char *File, LANKCSConfig_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->AMI_Dynamic_LANIfcSupport = IniGetUInt(ini, "LANKCSConfig", "AMI_Dynamic_LANIfcSupport", 0x1);

	data->AMI_Dynamic_KCSIfcSupport = IniGetUInt(ini, "LANKCSConfig", "AMI_Dynamic_KCSIfcSupport", 0x1);

	IniCloseFile(ini);
	return 0;
}

int
LANKCSConfig_SaveFile(char *File, LANKCSConfig_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "LANKCSConfig", "AMI_Dynamic_LANIfcSupport", data->AMI_Dynamic_LANIfcSupport);

	IniSetUInt(ini, "LANKCSConfig", "AMI_Dynamic_KCSIfcSupport", data->AMI_Dynamic_KCSIfcSupport);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

