/*------------------------------------------------------------*
 * misccfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	/* MISC Configuration */
	#include "Types.h"
	#include "PMConfig.h"
	
int
MiscConfig_LoadFile(char *File, MiscConfig_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	strncpy((char*)data->SyslogHostname, IniGetStr(ini, "MISCCfg", "SyslogHostname", "0.0.0.0"), 64);

	data->SyslogPort = IniGetUInt(ini, "MISCCfg", "SyslogPort", 0);

	data->SyslogEnable = IniGetUInt(ini, "MISCCfg", "SyslogEnable", 0x0);

	data->SnmpPort = IniGetUInt(ini, "MISCCfg", "SnmpPort", 0);

	strncpy((char*)data->TimeZone, IniGetStr(ini, "MISCCfg", "TimeZone", "America/New_York"), 64);

	IniCloseFile(ini);
	return 0;
}

int
MiscConfig_SaveFile(char *File, MiscConfig_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetStr(ini, "MISCCfg", "SyslogHostname", (char*)data->SyslogHostname);

	IniSetUInt(ini, "MISCCfg", "SyslogPort", data->SyslogPort);

	IniSetUInt(ini, "MISCCfg", "SyslogEnable", data->SyslogEnable);

	IniSetUInt(ini, "MISCCfg", "SnmpPort", data->SnmpPort);

	IniSetStr(ini, "MISCCfg", "TimeZone", (char*)data->TimeZone);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

