/*------------------------------------------------------------*
 * rmcppluscfg2.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	/* RMCPPlus Configuration */
	#include "PMConfig.h"
	#include "Types.h"
	
int
RMCPlus2_LoadFile(char *File, RMCPPlus_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->LockKey[0] = IniGetBool(ini, "RMCPPlus2Configuration", "LockKey/0", 0x0);
	data->LockKey[1] = IniGetBool(ini, "RMCPPlus2Configuration", "LockKey/1", 0x0);

	data->KGHashKey[0] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/0", 0);
	data->KGHashKey[1] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/1", 0);
	data->KGHashKey[2] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/2", 0);
	data->KGHashKey[3] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/3", 0);
	data->KGHashKey[4] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/4", 0);
	data->KGHashKey[5] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/5", 0);
	data->KGHashKey[6] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/6", 0);
	data->KGHashKey[7] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/7", 0);
	data->KGHashKey[8] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/8", 0);
	data->KGHashKey[9] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/9", 0);
	data->KGHashKey[10] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/10", 0);
	data->KGHashKey[11] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/11", 0);
	data->KGHashKey[12] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/12", 0);
	data->KGHashKey[13] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/13", 0);
	data->KGHashKey[14] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/14", 0);
	data->KGHashKey[15] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/15", 0);
	data->KGHashKey[16] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/16", 0);
	data->KGHashKey[17] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/17", 0);
	data->KGHashKey[18] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/18", 0);
	data->KGHashKey[19] = IniGetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/19", 0);

	data->PseudoGenKey[0] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/0", 0);
	data->PseudoGenKey[1] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/1", 0);
	data->PseudoGenKey[2] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/2", 0);
	data->PseudoGenKey[3] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/3", 0);
	data->PseudoGenKey[4] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/4", 0);
	data->PseudoGenKey[5] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/5", 0);
	data->PseudoGenKey[6] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/6", 0);
	data->PseudoGenKey[7] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/7", 0);
	data->PseudoGenKey[8] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/8", 0);
	data->PseudoGenKey[9] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/9", 0);
	data->PseudoGenKey[10] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/10", 0);
	data->PseudoGenKey[11] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/11", 0);
	data->PseudoGenKey[12] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/12", 0);
	data->PseudoGenKey[13] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/13", 0);
	data->PseudoGenKey[14] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/14", 0);
	data->PseudoGenKey[15] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/15", 0);
	data->PseudoGenKey[16] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/16", 0);
	data->PseudoGenKey[17] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/17", 0);
	data->PseudoGenKey[18] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/18", 0);
	data->PseudoGenKey[19] = IniGetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/19", 0);

	data->Algorithm[0][0] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/0", 0);
	data->Algorithm[0][1] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/1", 0x1  << 3 | 0x0  << 2  |  0x0  << 1  |  0x0);
	data->Algorithm[0][2] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/2", 0x1  << 3 | 0x0  << 2  |  0x0  << 1  |  0x0);
	data->Algorithm[0][3] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/3", 0x1  << 3 | 0x0  << 2  |  0x0  << 1  |  0x0);
	data->Algorithm[0][4] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/4", 0x1  << 3 | 0x0  << 2  |  0x0   << 1  |  0x0);
	data->Algorithm[0][5] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/5", 0x0 << 3 | 0x0  << 2  |  0x0 << 1  |  0x0);
	data->Algorithm[0][6] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/6", 0);
	data->Algorithm[1][0] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/0", 0);
	data->Algorithm[1][1] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/1", 0x1  << 4 | 0x0  << 3 | 0x0  << 2  | 0x0  << 1 | 0x0);
	data->Algorithm[1][2] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/2", 0x1  << 4 | 0x0  << 3 | 0x0  << 2  | 0x0  << 1 | 0x0);
	data->Algorithm[1][3] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/3", 0x1  << 4 | 0x0  << 3 | 0x0  << 2  | 0x0  << 1 | 0x0);
	data->Algorithm[1][4] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/4", 0x1  << 4 | 0x0  << 3 | 0x0  << 2  | 0x0  << 1 | 0x0);
	data->Algorithm[1][5] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/5", 0x0 << 4 | 0x0  << 3 | 0x0 << 2  | 0x0 << 1 | 0x0);
	data->Algorithm[1][6] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/6", 0);
	data->Algorithm[2][0] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/0", 0);
	data->Algorithm[2][1] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/1", 0x0 << 3 | 0x0 << 2 | 0x1 << 1 | 0x1);
	data->Algorithm[2][2] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/2", 0x0 << 3 | 0x0 << 2 | 0x1 << 1 | 0x1);
	data->Algorithm[2][3] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/3", 0x0 << 3 | 0x0 << 2 | 0x1 << 1 | 0x1);
	data->Algorithm[2][4] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/4", 0x0 << 3 | 0x0 << 2 | 0x1 << 1 | 0x1);
	data->Algorithm[2][5] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/5", 0x0 << 3 | 0x0 << 2 | 0x0 << 1 | 0x0);
	data->Algorithm[2][6] = IniGetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/6", 0);

	data->PayloadSupport.StandPldtype1 = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "StandPldtype1", (0x0 << 7) | (0x0 << 6) | (0x0 << 5) | (0x0 << 4) | \
			 (0x0 << 3) | (0x0 << 2) | (0x1 << 1) | 0x1);
	data->PayloadSupport.StandPldtype2 = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "StandPldtype2", (0x0 << 7) | (0x0 << 6) | (0x0 << 5) | (0x0 << 4) | \
			 (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);
	data->PayloadSupport.SessStpPldtype1 = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "SessStpPldtype1", (0x0 << 7) | (0x0 << 6) | (0x0 << 5) | (0x0 << 4) | \
			 (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);
	data->PayloadSupport.SessStpPldtype2 = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "SessStpPldtype2", (0x0 << 7) | (0x0 << 6) | (0x0 << 5) | (0x0 << 4) | \
			 (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);
	data->PayloadSupport.OemPldtype1 = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "OemPldtype1", (0x0 << 7) | (0x0 << 6) | (0x0 << 5) | (0x0 << 4)  | \
			 (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);
	data->PayloadSupport.OemPldtype2 = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "OemPldtype2", (0x0 << 7) | (0x0 << 6) | (0x0 << 5) | (0x0 << 4) | \
			 (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);

	data->PayloadInfo[0].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "Type", 0x0);
	data->PayloadInfo[0].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldIANA/0", 0);
	data->PayloadInfo[0].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldIANA/1", 0);
	data->PayloadInfo[0].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldIANA/2", 0);
	data->PayloadInfo[0].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldID/0", 0);
	data->PayloadInfo[0].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldID/1", 0);
	data->PayloadInfo[0].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "Version", 0x10);
	data->PayloadInfo[1].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "Type", 0x1);
	data->PayloadInfo[1].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldIANA/0", 0);
	data->PayloadInfo[1].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldIANA/1", 0);
	data->PayloadInfo[1].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldIANA/2", 0);
	data->PayloadInfo[1].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldID/0", 0);
	data->PayloadInfo[1].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldID/1", 0);
	data->PayloadInfo[1].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "Version", 0x10);
	data->PayloadInfo[2].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "Type", 0x2);
	data->PayloadInfo[2].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldIANA/0", 0);
	data->PayloadInfo[2].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldIANA/1", 0);
	data->PayloadInfo[2].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldIANA/2", 0);
	data->PayloadInfo[2].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldID/0", 0);
	data->PayloadInfo[2].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldID/1", 0);
	data->PayloadInfo[2].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "Version", 0x10);
	data->PayloadInfo[3].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "Type", 0x10);
	data->PayloadInfo[3].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldIANA/0", 0);
	data->PayloadInfo[3].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldIANA/1", 0);
	data->PayloadInfo[3].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldIANA/2", 0);
	data->PayloadInfo[3].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldID/0", 0);
	data->PayloadInfo[3].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldID/1", 0);
	data->PayloadInfo[3].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "Version", 0x10);
	data->PayloadInfo[4].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "Type", 0x11);
	data->PayloadInfo[4].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldIANA/0", 0);
	data->PayloadInfo[4].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldIANA/1", 0);
	data->PayloadInfo[4].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldIANA/2", 0);
	data->PayloadInfo[4].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldID/0", 0);
	data->PayloadInfo[4].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldID/1", 0);
	data->PayloadInfo[4].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "Version", 0x10);
	data->PayloadInfo[5].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "Type", 0x12);
	data->PayloadInfo[5].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldIANA/0", 0);
	data->PayloadInfo[5].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldIANA/1", 0);
	data->PayloadInfo[5].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldIANA/2", 0);
	data->PayloadInfo[5].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldID/0", 0);
	data->PayloadInfo[5].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldID/1", 0);
	data->PayloadInfo[5].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "Version", 0x10);
	data->PayloadInfo[6].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "Type", 0x13);
	data->PayloadInfo[6].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldIANA/0", 0);
	data->PayloadInfo[6].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldIANA/1", 0);
	data->PayloadInfo[6].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldIANA/2", 0);
	data->PayloadInfo[6].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldID/0", 0);
	data->PayloadInfo[6].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldID/1", 0);
	data->PayloadInfo[6].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "Version", 0x10);
	data->PayloadInfo[7].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "Type", 0x14);
	data->PayloadInfo[7].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldIANA/0", 0);
	data->PayloadInfo[7].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldIANA/1", 0);
	data->PayloadInfo[7].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldIANA/2", 0);
	data->PayloadInfo[7].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldID/0", 0);
	data->PayloadInfo[7].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldID/1", 0);
	data->PayloadInfo[7].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "Version", 0x10);
	data->PayloadInfo[8].Type = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "Type", 0x15);
	data->PayloadInfo[8].OemPldIANA[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldIANA/0", 0);
	data->PayloadInfo[8].OemPldIANA[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldIANA/1", 0);
	data->PayloadInfo[8].OemPldIANA[2] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldIANA/2", 0);
	data->PayloadInfo[8].OemPldID[0] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldID/0", 0);
	data->PayloadInfo[8].OemPldID[1] = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldID/1", 0);
	data->PayloadInfo[8].Version = IniGetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "Version", 0x10);

	IniCloseFile(ini);
	return 0;
}

int
RMCPlus2_SaveFile(char *File, RMCPPlus_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetBool(ini, "RMCPPlus2Configuration", "LockKey/0", data->LockKey[0]);
	IniSetBool(ini, "RMCPPlus2Configuration", "LockKey/1", data->LockKey[1]);

	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/0", data->KGHashKey[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/1", data->KGHashKey[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/2", data->KGHashKey[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/3", data->KGHashKey[3]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/4", data->KGHashKey[4]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/5", data->KGHashKey[5]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/6", data->KGHashKey[6]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/7", data->KGHashKey[7]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/8", data->KGHashKey[8]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/9", data->KGHashKey[9]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/10", data->KGHashKey[10]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/11", data->KGHashKey[11]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/12", data->KGHashKey[12]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/13", data->KGHashKey[13]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/14", data->KGHashKey[14]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/15", data->KGHashKey[15]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/16", data->KGHashKey[16]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/17", data->KGHashKey[17]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/18", data->KGHashKey[18]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "KGHashKey/19", data->KGHashKey[19]);

	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/0", data->PseudoGenKey[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/1", data->PseudoGenKey[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/2", data->PseudoGenKey[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/3", data->PseudoGenKey[3]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/4", data->PseudoGenKey[4]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/5", data->PseudoGenKey[5]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/6", data->PseudoGenKey[6]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/7", data->PseudoGenKey[7]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/8", data->PseudoGenKey[8]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/9", data->PseudoGenKey[9]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/10", data->PseudoGenKey[10]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/11", data->PseudoGenKey[11]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/12", data->PseudoGenKey[12]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/13", data->PseudoGenKey[13]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/14", data->PseudoGenKey[14]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/15", data->PseudoGenKey[15]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/16", data->PseudoGenKey[16]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/17", data->PseudoGenKey[17]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/18", data->PseudoGenKey[18]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "PseudoGenKey/19", data->PseudoGenKey[19]);

	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/0", data->Algorithm[0][0]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/1", data->Algorithm[0][1]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/2", data->Algorithm[0][2]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/3", data->Algorithm[0][3]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/4", data->Algorithm[0][4]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/5", data->Algorithm[0][5]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/0/6", data->Algorithm[0][6]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/0", data->Algorithm[1][0]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/1", data->Algorithm[1][1]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/2", data->Algorithm[1][2]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/3", data->Algorithm[1][3]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/4", data->Algorithm[1][4]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/5", data->Algorithm[1][5]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/1/6", data->Algorithm[1][6]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/0", data->Algorithm[2][0]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/1", data->Algorithm[2][1]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/2", data->Algorithm[2][2]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/3", data->Algorithm[2][3]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/4", data->Algorithm[2][4]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/5", data->Algorithm[2][5]);
	IniSetUInt(ini, "RMCPPlus2Configuration", "Algorithm/2/6", data->Algorithm[2][6]);

	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "StandPldtype1", data->PayloadSupport.StandPldtype1);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "StandPldtype2", data->PayloadSupport.StandPldtype2);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "SessStpPldtype1", data->PayloadSupport.SessStpPldtype1);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "SessStpPldtype2", data->PayloadSupport.SessStpPldtype2);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "OemPldtype1", data->PayloadSupport.OemPldtype1);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadSupport", "OemPldtype2", data->PayloadSupport.OemPldtype2);

	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "Type", data->PayloadInfo[0].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldIANA/0", data->PayloadInfo[0].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldIANA/1", data->PayloadInfo[0].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldIANA/2", data->PayloadInfo[0].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldID/0", data->PayloadInfo[0].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "OemPldID/1", data->PayloadInfo[0].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/0", "Version", data->PayloadInfo[0].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "Type", data->PayloadInfo[1].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldIANA/0", data->PayloadInfo[1].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldIANA/1", data->PayloadInfo[1].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldIANA/2", data->PayloadInfo[1].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldID/0", data->PayloadInfo[1].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "OemPldID/1", data->PayloadInfo[1].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/1", "Version", data->PayloadInfo[1].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "Type", data->PayloadInfo[2].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldIANA/0", data->PayloadInfo[2].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldIANA/1", data->PayloadInfo[2].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldIANA/2", data->PayloadInfo[2].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldID/0", data->PayloadInfo[2].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "OemPldID/1", data->PayloadInfo[2].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/2", "Version", data->PayloadInfo[2].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "Type", data->PayloadInfo[3].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldIANA/0", data->PayloadInfo[3].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldIANA/1", data->PayloadInfo[3].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldIANA/2", data->PayloadInfo[3].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldID/0", data->PayloadInfo[3].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "OemPldID/1", data->PayloadInfo[3].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/3", "Version", data->PayloadInfo[3].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "Type", data->PayloadInfo[4].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldIANA/0", data->PayloadInfo[4].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldIANA/1", data->PayloadInfo[4].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldIANA/2", data->PayloadInfo[4].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldID/0", data->PayloadInfo[4].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "OemPldID/1", data->PayloadInfo[4].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/4", "Version", data->PayloadInfo[4].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "Type", data->PayloadInfo[5].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldIANA/0", data->PayloadInfo[5].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldIANA/1", data->PayloadInfo[5].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldIANA/2", data->PayloadInfo[5].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldID/0", data->PayloadInfo[5].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "OemPldID/1", data->PayloadInfo[5].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/5", "Version", data->PayloadInfo[5].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "Type", data->PayloadInfo[6].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldIANA/0", data->PayloadInfo[6].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldIANA/1", data->PayloadInfo[6].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldIANA/2", data->PayloadInfo[6].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldID/0", data->PayloadInfo[6].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "OemPldID/1", data->PayloadInfo[6].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/6", "Version", data->PayloadInfo[6].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "Type", data->PayloadInfo[7].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldIANA/0", data->PayloadInfo[7].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldIANA/1", data->PayloadInfo[7].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldIANA/2", data->PayloadInfo[7].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldID/0", data->PayloadInfo[7].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "OemPldID/1", data->PayloadInfo[7].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/7", "Version", data->PayloadInfo[7].Version);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "Type", data->PayloadInfo[8].Type);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldIANA/0", data->PayloadInfo[8].OemPldIANA[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldIANA/1", data->PayloadInfo[8].OemPldIANA[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldIANA/2", data->PayloadInfo[8].OemPldIANA[2]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldID/0", data->PayloadInfo[8].OemPldID[0]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "OemPldID/1", data->PayloadInfo[8].OemPldID[1]);
	IniSetUInt(ini, "RMCPPlus2Configuration/PayloadInfo/8", "Version", data->PayloadInfo[8].Version);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}


	/* End RMCP Plus Configuration */
	