/*------------------------------------------------------------*
 * smmchannel.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "PMConfig.h"
	#include "Types.h"
	
int
SMMChannelInfo_LoadFile(char *File, ChannelInfo_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->ID = IniGetUInt(ini, "SMMChannelInformation", "ID", 0x43484944);

	data->ChannelIndex = IniGetUInt(ini, "SMMChannelInformation", "ChannelIndex", 7);

	data->ChannelNumber = IniGetUInt(ini, "SMMChannelInformation", "ChannelNumber", 0x5);

	data->ChannelType = IniGetUInt(ini, "SMMChannelInformation", "ChannelType", 0x8);

	data->ChannelMedium = IniGetUInt(ini, "SMMChannelInformation", "ChannelMedium", 0xc);

	data->ChannelProtocol = IniGetUInt(ini, "SMMChannelInformation", "ChannelProtocol", 0x5);

	data->SessionSupport = IniGetUInt(ini, "SMMChannelInformation", "SessionSupport", 0x0);

	data->ActiveSession = IniGetUInt(ini, "SMMChannelInformation", "ActiveSession", 0x0);

	data->AuthType[0] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/0", 0);
	data->AuthType[1] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/1", 0);
	data->AuthType[2] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/2", 0);
	data->AuthType[3] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/3", 0);
	data->AuthType[4] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/4", 0);
	data->AuthType[5] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/5", 0);
	data->AuthType[6] = IniGetUInt(ini, "SMMChannelInformation", "AuthType/6", 0);

	data->ProtocolVendorId[0] = IniGetUInt(ini, "SMMChannelInformation", "ProtocolVendorId/0", (0xf21b00 & 0xFF0000) >> 16);
	data->ProtocolVendorId[1] = IniGetUInt(ini, "SMMChannelInformation", "ProtocolVendorId/1", \
			(0xf21b00 & 0xFF00) >> 8);
	data->ProtocolVendorId[2] = IniGetUInt(ini, "SMMChannelInformation", "ProtocolVendorId/2", (0xf21b00 & 0xFF));

	data->AuxiliaryInfo[0] = IniGetUInt(ini, "SMMChannelInformation", "AuxiliaryInfo/0", (0xffff & 0xFF00) >> 8);
	data->AuxiliaryInfo[1] = IniGetUInt(ini, "SMMChannelInformation", "AuxiliaryInfo/1", (0xffff & 0xFF));

	data->ReceiveMsgQ = IniGetUInt(ini, "SMMChannelInformation", "ReceiveMsgQ", 1);

	data->AccessMode = IniGetUInt(ini, "SMMChannelInformation", "AccessMode", 0x2);

	data->AccessModeSupported = IniGetUInt(ini, "SMMChannelInformation", "AccessModeSupported", 0);

	data->Alerting = IniGetUInt(ini, "SMMChannelInformation", "Alerting", 0x0);

	data->PerMessageAuth = IniGetUInt(ini, "SMMChannelInformation", "PerMessageAuth", 0x0);

	data->UserLevelAuth = IniGetUInt(ini, "SMMChannelInformation", "UserLevelAuth", 0x0);

	data->MaxPrivilege = IniGetUInt(ini, "SMMChannelInformation", "MaxPrivilege", 0);

	data->reserved = IniGetUInt(ini, "SMMChannelInformation", "reserved", 0);

	data->SetUserAccess = IniGetUInt(ini, "SMMChannelInformation", "SetUserAccess", 0x0);

	data->SetChPrivilege = IniGetUInt(ini, "SMMChannelInformation", "SetChPrivilege", 0x0);

	data->SessionLimit = IniGetUInt(ini, "SMMChannelInformation", "SessionLimit", 0);

	data->LoginStatusNUP = IniGetUInt(ini, "SMMChannelInformation", "LoginStatusNUP", 0);

	data->LoginStatusNUNP = IniGetUInt(ini, "SMMChannelInformation", "LoginStatusNUNP", 0);

	data->LoginStatusNNU = IniGetUInt(ini, "SMMChannelInformation", "LoginStatusNNU", 0);

	data->MaxUser = IniGetUInt(ini, "SMMChannelInformation", "MaxUser", 0);

	data->NoCurrentUser = IniGetUInt(ini, "SMMChannelInformation", "NoCurrentUser", 0);

	data->NoFixedUser = IniGetUInt(ini, "SMMChannelInformation", "NoFixedUser", 0);


	data->ChannelIndexNvRam = IniGetUInt(ini, "SMMChannelInformation", "ChannelIndexNvRam", 0);

	data->ChannelUserInfo[0].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "ID", (((INT32U)'U'<<24) | ((INT32U)'S'<<16) | ('E'<<8) | ('R') ));
	data->ChannelUserInfo[0].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserId", 0);
	data->ChannelUserInfo[0].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "AccessLimit", 0xf);
	data->ChannelUserInfo[0].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "LinkAuth", 0x0);
	data->ChannelUserInfo[0].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserAccessCallback", 0x0);
	data->ChannelUserInfo[0].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserAccessCBCPCallback", 0x0);
	data->ChannelUserInfo[0].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[1].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "ID", (((INT32U)'U'<<24) | ((INT32U)'S'<<16) | ('E'<<8) | ('R') ));
	data->ChannelUserInfo[1].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserId", 0);
	data->ChannelUserInfo[1].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "AccessLimit", 0xf);
	data->ChannelUserInfo[1].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "LinkAuth", 0x0);
	data->ChannelUserInfo[1].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserAccessCallback", 0x0);
	data->ChannelUserInfo[1].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserAccessCBCPCallback", 0x0);
	data->ChannelUserInfo[1].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[2].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "ID", 0);
	data->ChannelUserInfo[2].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserId", 0);
	data->ChannelUserInfo[2].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "AccessLimit", 0);
	data->ChannelUserInfo[2].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "LinkAuth", 0);
	data->ChannelUserInfo[2].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserAccessCallback", 0);
	data->ChannelUserInfo[2].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[2].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[3].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "ID", 0);
	data->ChannelUserInfo[3].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserId", 0);
	data->ChannelUserInfo[3].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "AccessLimit", 0);
	data->ChannelUserInfo[3].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "LinkAuth", 0);
	data->ChannelUserInfo[3].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserAccessCallback", 0);
	data->ChannelUserInfo[3].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[3].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[4].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "ID", 0);
	data->ChannelUserInfo[4].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserId", 0);
	data->ChannelUserInfo[4].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "AccessLimit", 0);
	data->ChannelUserInfo[4].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "LinkAuth", 0);
	data->ChannelUserInfo[4].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserAccessCallback", 0);
	data->ChannelUserInfo[4].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[4].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[5].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "ID", 0);
	data->ChannelUserInfo[5].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserId", 0);
	data->ChannelUserInfo[5].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "AccessLimit", 0);
	data->ChannelUserInfo[5].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "LinkAuth", 0);
	data->ChannelUserInfo[5].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserAccessCallback", 0);
	data->ChannelUserInfo[5].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[5].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[6].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "ID", 0);
	data->ChannelUserInfo[6].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserId", 0);
	data->ChannelUserInfo[6].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "AccessLimit", 0);
	data->ChannelUserInfo[6].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "LinkAuth", 0);
	data->ChannelUserInfo[6].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserAccessCallback", 0);
	data->ChannelUserInfo[6].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[6].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[7].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "ID", 0);
	data->ChannelUserInfo[7].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserId", 0);
	data->ChannelUserInfo[7].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "AccessLimit", 0);
	data->ChannelUserInfo[7].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "LinkAuth", 0);
	data->ChannelUserInfo[7].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserAccessCallback", 0);
	data->ChannelUserInfo[7].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[7].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[8].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "ID", 0);
	data->ChannelUserInfo[8].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserId", 0);
	data->ChannelUserInfo[8].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "AccessLimit", 0);
	data->ChannelUserInfo[8].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "LinkAuth", 0);
	data->ChannelUserInfo[8].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserAccessCallback", 0);
	data->ChannelUserInfo[8].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[8].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserCallbackCapabilities", 0);
	data->ChannelUserInfo[9].ID = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "ID", 0);
	data->ChannelUserInfo[9].UserId = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserId", 0);
	data->ChannelUserInfo[9].AccessLimit = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "AccessLimit", 0);
	data->ChannelUserInfo[9].LinkAuth = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "LinkAuth", 0);
	data->ChannelUserInfo[9].UserAccessCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserAccessCallback", 0);
	data->ChannelUserInfo[9].UserAccessCBCPCallback = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserAccessCBCPCallback", 0);
	data->ChannelUserInfo[9].UserCallbackCapabilities = IniGetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserCallbackCapabilities", 0);

	IniCloseFile(ini);
	return 0;
}

int
SMMChannelInfo_SaveFile(char *File, ChannelInfo_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "SMMChannelInformation", "ID", data->ID);

	IniSetUInt(ini, "SMMChannelInformation", "ChannelIndex", data->ChannelIndex);

	IniSetUInt(ini, "SMMChannelInformation", "ChannelNumber", data->ChannelNumber);

	IniSetUInt(ini, "SMMChannelInformation", "ChannelType", data->ChannelType);

	IniSetUInt(ini, "SMMChannelInformation", "ChannelMedium", data->ChannelMedium);

	IniSetUInt(ini, "SMMChannelInformation", "ChannelProtocol", data->ChannelProtocol);

	IniSetUInt(ini, "SMMChannelInformation", "SessionSupport", data->SessionSupport);

	IniSetUInt(ini, "SMMChannelInformation", "ActiveSession", data->ActiveSession);

	IniSetUInt(ini, "SMMChannelInformation", "AuthType/0", data->AuthType[0]);
	IniSetUInt(ini, "SMMChannelInformation", "AuthType/1", data->AuthType[1]);
	IniSetUInt(ini, "SMMChannelInformation", "AuthType/2", data->AuthType[2]);
	IniSetUInt(ini, "SMMChannelInformation", "AuthType/3", data->AuthType[3]);
	IniSetUInt(ini, "SMMChannelInformation", "AuthType/4", data->AuthType[4]);
	IniSetUInt(ini, "SMMChannelInformation", "AuthType/5", data->AuthType[5]);
	IniSetUInt(ini, "SMMChannelInformation", "AuthType/6", data->AuthType[6]);

	IniSetUInt(ini, "SMMChannelInformation", "ProtocolVendorId/0", data->ProtocolVendorId[0]);
	IniSetUInt(ini, "SMMChannelInformation", "ProtocolVendorId/1", data->ProtocolVendorId[1]);
	IniSetUInt(ini, "SMMChannelInformation", "ProtocolVendorId/2", data->ProtocolVendorId[2]);

	IniSetUInt(ini, "SMMChannelInformation", "AuxiliaryInfo/0", data->AuxiliaryInfo[0]);
	IniSetUInt(ini, "SMMChannelInformation", "AuxiliaryInfo/1", data->AuxiliaryInfo[1]);

	IniSetUInt(ini, "SMMChannelInformation", "ReceiveMsgQ", data->ReceiveMsgQ);

	IniSetUInt(ini, "SMMChannelInformation", "AccessMode", data->AccessMode);

	IniSetUInt(ini, "SMMChannelInformation", "AccessModeSupported", data->AccessModeSupported);

	IniSetUInt(ini, "SMMChannelInformation", "Alerting", data->Alerting);

	IniSetUInt(ini, "SMMChannelInformation", "PerMessageAuth", data->PerMessageAuth);

	IniSetUInt(ini, "SMMChannelInformation", "UserLevelAuth", data->UserLevelAuth);

	IniSetUInt(ini, "SMMChannelInformation", "MaxPrivilege", data->MaxPrivilege);

	IniSetUInt(ini, "SMMChannelInformation", "reserved", data->reserved);

	IniSetUInt(ini, "SMMChannelInformation", "SetUserAccess", data->SetUserAccess);

	IniSetUInt(ini, "SMMChannelInformation", "SetChPrivilege", data->SetChPrivilege);

	IniSetUInt(ini, "SMMChannelInformation", "SessionLimit", data->SessionLimit);

	IniSetUInt(ini, "SMMChannelInformation", "LoginStatusNUP", data->LoginStatusNUP);

	IniSetUInt(ini, "SMMChannelInformation", "LoginStatusNUNP", data->LoginStatusNUNP);

	IniSetUInt(ini, "SMMChannelInformation", "LoginStatusNNU", data->LoginStatusNNU);

	IniSetUInt(ini, "SMMChannelInformation", "MaxUser", data->MaxUser);

	IniSetUInt(ini, "SMMChannelInformation", "NoCurrentUser", data->NoCurrentUser);

	IniSetUInt(ini, "SMMChannelInformation", "NoFixedUser", data->NoFixedUser);


	IniSetUInt(ini, "SMMChannelInformation", "ChannelIndexNvRam", data->ChannelIndexNvRam);

	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "ID", data->ChannelUserInfo[0].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserId", data->ChannelUserInfo[0].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "AccessLimit", data->ChannelUserInfo[0].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "LinkAuth", data->ChannelUserInfo[0].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserAccessCallback", data->ChannelUserInfo[0].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserAccessCBCPCallback", data->ChannelUserInfo[0].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/0", "UserCallbackCapabilities", data->ChannelUserInfo[0].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "ID", data->ChannelUserInfo[1].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserId", data->ChannelUserInfo[1].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "AccessLimit", data->ChannelUserInfo[1].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "LinkAuth", data->ChannelUserInfo[1].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserAccessCallback", data->ChannelUserInfo[1].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserAccessCBCPCallback", data->ChannelUserInfo[1].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/1", "UserCallbackCapabilities", data->ChannelUserInfo[1].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "ID", data->ChannelUserInfo[2].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserId", data->ChannelUserInfo[2].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "AccessLimit", data->ChannelUserInfo[2].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "LinkAuth", data->ChannelUserInfo[2].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserAccessCallback", data->ChannelUserInfo[2].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserAccessCBCPCallback", data->ChannelUserInfo[2].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/2", "UserCallbackCapabilities", data->ChannelUserInfo[2].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "ID", data->ChannelUserInfo[3].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserId", data->ChannelUserInfo[3].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "AccessLimit", data->ChannelUserInfo[3].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "LinkAuth", data->ChannelUserInfo[3].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserAccessCallback", data->ChannelUserInfo[3].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserAccessCBCPCallback", data->ChannelUserInfo[3].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/3", "UserCallbackCapabilities", data->ChannelUserInfo[3].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "ID", data->ChannelUserInfo[4].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserId", data->ChannelUserInfo[4].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "AccessLimit", data->ChannelUserInfo[4].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "LinkAuth", data->ChannelUserInfo[4].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserAccessCallback", data->ChannelUserInfo[4].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserAccessCBCPCallback", data->ChannelUserInfo[4].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/4", "UserCallbackCapabilities", data->ChannelUserInfo[4].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "ID", data->ChannelUserInfo[5].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserId", data->ChannelUserInfo[5].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "AccessLimit", data->ChannelUserInfo[5].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "LinkAuth", data->ChannelUserInfo[5].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserAccessCallback", data->ChannelUserInfo[5].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserAccessCBCPCallback", data->ChannelUserInfo[5].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/5", "UserCallbackCapabilities", data->ChannelUserInfo[5].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "ID", data->ChannelUserInfo[6].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserId", data->ChannelUserInfo[6].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "AccessLimit", data->ChannelUserInfo[6].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "LinkAuth", data->ChannelUserInfo[6].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserAccessCallback", data->ChannelUserInfo[6].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserAccessCBCPCallback", data->ChannelUserInfo[6].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/6", "UserCallbackCapabilities", data->ChannelUserInfo[6].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "ID", data->ChannelUserInfo[7].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserId", data->ChannelUserInfo[7].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "AccessLimit", data->ChannelUserInfo[7].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "LinkAuth", data->ChannelUserInfo[7].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserAccessCallback", data->ChannelUserInfo[7].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserAccessCBCPCallback", data->ChannelUserInfo[7].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/7", "UserCallbackCapabilities", data->ChannelUserInfo[7].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "ID", data->ChannelUserInfo[8].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserId", data->ChannelUserInfo[8].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "AccessLimit", data->ChannelUserInfo[8].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "LinkAuth", data->ChannelUserInfo[8].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserAccessCallback", data->ChannelUserInfo[8].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserAccessCBCPCallback", data->ChannelUserInfo[8].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/8", "UserCallbackCapabilities", data->ChannelUserInfo[8].UserCallbackCapabilities);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "ID", data->ChannelUserInfo[9].ID);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserId", data->ChannelUserInfo[9].UserId);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "AccessLimit", data->ChannelUserInfo[9].AccessLimit);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "LinkAuth", data->ChannelUserInfo[9].LinkAuth);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserAccessCallback", data->ChannelUserInfo[9].UserAccessCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserAccessCBCPCallback", data->ChannelUserInfo[9].UserAccessCBCPCallback);
	IniSetUInt(ini, "SMMChannelInformation/ChannelUserInfo/9", "UserCallbackCapabilities", data->ChannelUserInfo[9].UserCallbackCapabilities);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}


	/* End SMM Channel Configuration */
	