/*------------------------------------------------------------*
 * soltriggereventcfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "PMConfig.h"
	#include "Types.h"
	
int
SOLTriggerEvtConfigTable_LoadFile(char *File, SOLTriggerEventCfg_T *Trigger)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	Trigger->CriticalFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "CriticalFlag", 0);

	Trigger->NONCriticalFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "NONCriticalFlag", 0);

	Trigger->NONRecoverableFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "NONRecoverableFlag", 0);

	Trigger->FanTroubled = IniGetUInt(ini, "SOLTriggerEventConfiguration", "FanTroubled", 0);

	Trigger->WDTTimeExpire = IniGetUInt(ini, "SOLTriggerEventConfiguration", "WDTTimeExpire", 0);

	Trigger->SysDConFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "SysDConFlag", 0);

	Trigger->SysDCoffFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "SysDCoffFlag", 0);

	Trigger->SysResetFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "SysResetFlag", 0);

	Trigger->LPCResetFlag = IniGetUInt(ini, "SOLTriggerEventConfiguration", "LPCResetFlag", 0);

	Trigger->SpecDateTime = IniGetUInt(ini, "SOLTriggerEventConfiguration", "SpecDateTime", 0);

	Trigger->Time = IniGetUInt(ini, "SOLTriggerEventConfiguration", "Time", 0x0);

	IniCloseFile(ini);
	return 0;
}

int
SOLTriggerEvtConfigTable_SaveFile(char *File, SOLTriggerEventCfg_T *Trigger)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "CriticalFlag", Trigger->CriticalFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "NONCriticalFlag", Trigger->NONCriticalFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "NONRecoverableFlag", Trigger->NONRecoverableFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "FanTroubled", Trigger->FanTroubled);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "WDTTimeExpire", Trigger->WDTTimeExpire);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "SysDConFlag", Trigger->SysDConFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "SysDCoffFlag", Trigger->SysDCoffFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "SysResetFlag", Trigger->SysResetFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "LPCResetFlag", Trigger->LPCResetFlag);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "SpecDateTime", Trigger->SpecDateTime);

	IniSetUInt(ini, "SOLTriggerEventConfiguration", "Time", Trigger->Time);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

