/*------------------------------------------------------------*
 * ast2600evb.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */                                              

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2007-2013, American Megatrends Inc.        **
 **                                                            **
 **                 All Rights Reserved.                       **
 **                                                            **
 **     5555 Oakbrook Parkway, Building 200, Norcross,         **
 **                                                            **
 **      Georgia - 30093, USA. Phone-(770)-246-8600.           **
 **                                                            **
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <math.h>
#include "hal_api.h"
#include "hal_hw.h"
#include "SensorMonitor.h"
#include "PDKHooks.h"
#include "IPMIConf.h"
#include "mmap.h"

#define BMC_INST           			1
#define FRU_TYPE_NVR	   			1
#define SEN_NOT_ACCESSABLE			0xc5
#define ENBALE_DEBUG_MACROS 		1
#define WOLFPASS_TOTAL_SYSTEM_FANS	6
#define WOLFPASS_TOTAL_CPUS			2
#define DUMMY_NORMAL_VALUE 			0x00

int g_fanPresence[WOLFPASS_TOTAL_SYSTEM_FANS] = { 0 };
int g_CPUMissingInfo[WOLFPASS_TOTAL_CPUS] 	  = { 0 };
int g_CPUTjMax[WOLFPASS_TOTAL_CPUS] 		  = { 0 };
//int g_SASModPresence 						  = 0;
//int g_IOModPresence 						  = 0;

/* GPIO Functions - */
#define  GET_MODULE_PROPERTIES   0
#define  GET_GPIO_DIRECTION  	 1
#define  SET_GPIO_DIRECTION      2
#define  GET_GPIO_POLARITY       3
#define  SET_GPIO_POLARITY       4
#define  READ_GPIO		  		 5
#define  WRITE_GPIO		  		 6

#define LOCK_FILE_WRITE(hFile)                        \
if (-1 == file_lock_write (hFile))                      \
{                                                       \
    IPMI_WARNING ("NVRAcces.c : Error locking File\n"); \
}

#define LOCK_FILE_READ(hFile)                          \
if(-1 == file_lock_read(hFile))                         \
{                                                       \
    IPMI_WARNING("NVRAccess.c: Error locking File\n"); \
}

#define UNLOCK_FILE(hFile)                              \
if (-1 == file_unlock (hFile))                          \
{                                                       \
    IPMI_WARNING ("NVRAccess.c : Error unlocking File\n");     \
} 

/* Sensor Properties Structure */
typedef struct {
    INT8U  Reserved1;       /* Reserved 1 */
    INT8U  Reserved2;       /* Reserved 2 */
    INT16U  Reserved3;       /* Reserved 3 */
    INT8U  Reserved4;       /* Reserved 4 */
    INT8U  Reserved5;       /* Reserved 5 */
}SensorProp_T;

/* Interrupt Properties Structure */
typedef struct {
    INT8U	Reserved1;
    INT16U	SensorNum;
    INT32U	SensorType;
    INT32U	InteruptMethod;
    INT32U	InterruptType;
}Interuppt_T;


/* Device Access Function Declarations */

int dev_hyvepsusts_0x30h_1_32_init         (hal_t *phal);
int dev_hyvepsusts_0x30h_1_32_read         (hal_t *phal);
int dev_hyvepsusts_0x30h_1_32_write        (hal_t *phal);
int dev_hyvepsusts_0x30h_1_32_init_device  (hal_t *phal);
int dev_hyvepsusts_0x30h_1_32_read_device  (hal_t *phal);
int dev_hyvepsusts_0x30h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x31h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x31h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x31h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x31h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x31h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x31h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x32h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x32h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x32h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x32h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x32h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x32h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x33h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x33h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x33h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x33h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x33h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x33h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x34h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x34h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x34h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x34h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x34h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x34h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x35h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x35h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x35h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x35h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x35h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x35h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x36h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x36h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x36h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x36h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x36h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x36h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x37h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x37h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x37h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x37h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x37h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x37h_1_32_write_device (hal_t *phal);
int dev_hyvepsusts_0x38h_1_32_init         (hal_t *phal);
int dev_hyvepsusts_0x38h_1_32_read         (hal_t *phal);
int dev_hyvepsusts_0x38h_1_32_write        (hal_t *phal);
int dev_hyvepsusts_0x38h_1_32_init_device  (hal_t *phal);
int dev_hyvepsusts_0x38h_1_32_read_device  (hal_t *phal);
int dev_hyvepsusts_0x38h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x39h_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x39h_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x39h_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x39h_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x39h_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x39h_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x3ah_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x3ah_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x3ah_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x3ah_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x3ah_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x3ah_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x3bh_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x3bh_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x3bh_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x3bh_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x3bh_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x3bh_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x3ch_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x3ch_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x3ch_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x3ch_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x3ch_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x3ch_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x3dh_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x3dh_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x3dh_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x3dh_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x3dh_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x3dh_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x3eh_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x3eh_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x3eh_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x3eh_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x3eh_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x3eh_1_32_write_device (hal_t *phal);
int dev_hyvepsureadings_0x3fh_1_32_init         (hal_t *phal);
int dev_hyvepsureadings_0x3fh_1_32_read         (hal_t *phal);
int dev_hyvepsureadings_0x3fh_1_32_write        (hal_t *phal);
int dev_hyvepsureadings_0x3fh_1_32_init_device  (hal_t *phal);
int dev_hyvepsureadings_0x3fh_1_32_read_device  (hal_t *phal);
int dev_hyvepsureadings_0x3fh_1_32_write_device (hal_t *phal);
int dev_ast2600_init         (hal_t *phal);
int dev_ast2600_read         (hal_t *phal);
int dev_ast2600_write        (hal_t *phal);
int dev_ast2600_init_device  (hal_t *phal);
int dev_ast2600_read_device  (hal_t *phal);
int dev_ast2600_write_device (hal_t *phal);
int dev_mb_fru_init         (hal_t *phal);
int dev_mb_fru_read         (hal_t *phal);
int dev_mb_fru_write        (hal_t *phal);
int dev_mb_fru_init_device  (hal_t *phal);
int dev_mb_fru_read_device  (hal_t *phal);
int dev_mb_fru_write_device (hal_t *phal);


/**
 * Exported Defintions 
 **/



	

	
	
	
	SensorProp_T dev_hyvepsusts_0x30h_1_32_properties = {  
		3,
		0x1,
		0,
		0,
		0,
		
	};
	
	          
	
    
    static INT8U CURR_PSU0CIN_previous_value = 0x97;
    static INT8U CURR_PSU0CIN_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x31h_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U CURR_PSU0COUT_previous_value = 0x97;
    static INT8U CURR_PSU0COUT_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x32h_1_32_properties = {  
        1,
        0x0,
        DUMMY_NORMAL_VALUE,
        5,
        5,
        
    };
    
              
    
    
    static INT8U PWR_PSU0PIN_previous_value = 0x97;
    static INT8U PWR_PSU0PIN_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x33h_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U PWR_PSU0POUT_previous_value = 0x97;
    static INT8U PWR_PSU0POUT_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x34h_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U VOLT_PSU0_previous_value = 0x97;
    static INT8U VOLT_PSU0_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x35h_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U TEMP_PSU0_previous_value = 0x97;
    static INT8U TEMP_PSU0_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x36h_1_32_properties = {  
        1,
        0x0,
        DUMMY_NORMAL_VALUE,
        3,
        3,
        
    };
    
              
    
    
    static INT8U TACH_PSU0Fan0_previous_value = 0x97;
    static INT8U TACH_PSU0Fan0_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x37h_1_32_properties = {  
        3,
        0x0,
        DUMMY_NORMAL_VALUE,
        5,
        5,
        
    };
    
              
    
	

	
	
	
	SensorProp_T dev_hyvepsusts_0x38h_1_32_properties = {  
		3,
		0x1,
		0,
		0,
		0,
		
	};
	
	          
	
    
    static INT8U CURR_PSU1CIN_previous_value = 0x97;
    static INT8U CURR_PSU1CIN_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x39h_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U CURR_PSU1COUT_previous_value = 0x97;
    static INT8U CURR_PSU1COUT_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x3ah_1_32_properties = {  
        1,
        0x0,
        DUMMY_NORMAL_VALUE,
        5,
        5,
        
    };
    
              
    
    
    static INT8U PWR_PSU1PIN_previous_value = 0x97;
    static INT8U PWR_PSU1PIN_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x3bh_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U PWR_PSU1POUT_previous_value = 0x97;
    static INT8U PWR_PSU1POUT_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x3ch_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U VOLT_PSU1_previous_value = 0x97;
    static INT8U VOLT_PSU1_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x3dh_1_32_properties = {  
        1,
        0x1,
        DUMMY_NORMAL_VALUE,
        0,
        0,
        
    };
    
              
    
    
    static INT8U TEMP_PSU1_previous_value = 0x97;
    static INT8U TEMP_PSU1_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x3eh_1_32_properties = {  
        1,
        0x0,
        DUMMY_NORMAL_VALUE,
        3,
        3,
        
    };
    
              
    
    
    static INT8U TACH_PSU1Fan0_previous_value = 0x97;
    static INT8U TACH_PSU1Fan0_retry = 0;

    
    /* Temp sensor Properties */
    
    SensorProp_T dev_hyvepsureadings_0x3fh_1_32_properties = {  
        3,
        0x0,
        DUMMY_NORMAL_VALUE,
        5,
        5,
        
    };
    
              
    
         	
     
             
             
                 
             SensorProp_T dev_mb_fru_properties = {  
                             0,
                             0,
                             0,
                             0,
                             0,

                       };
                       
                       
    


/* Total No of Sensors Available */
const int  g_total_sensors =  16;

long long g_sensor_platform_tbl [] = 
{
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
		0xffffffffffffffff,
};

/** 
  * Sensor Table:
  * -------------
  *     Field 		Size          Purpose
  *     -------------------------------------------------------------
  *      1             2           Sensor Instance
  *      2             2           Sensor Number
  *      3             2           Sensor Device ID
  *      4             2           Sensor Read Function Pointer
  *      5             2           Sensor Write Function Pointer
  *      6             2           Sensor Init	Function Pointer
  *      7             2           Sensor Device Properties
  *      8             2           Sensor Device Properties Length
  **/
device_tbl_t g_sensor_tbl [] = 
{
	{ 
		0,
		((0x01 & 0x03) << 8) | 0x30,
		0xffff,
		dev_hyvepsusts_0x30h_1_32_read,
		dev_hyvepsusts_0x30h_1_32_write,
		dev_hyvepsusts_0x30h_1_32_init,
		&dev_hyvepsusts_0x30h_1_32_properties,
		sizeof(dev_hyvepsusts_0x30h_1_32_properties),
	}, 
	{ 
		0,
		((0x01 & 0x03) << 8) | 0x31,
		0xFFFF,
		dev_hyvepsureadings_0x31h_1_32_read,
		dev_hyvepsureadings_0x31h_1_32_write,
		dev_hyvepsureadings_0x31h_1_32_init,
		&dev_hyvepsureadings_0x31h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x31h_1_32_properties),
	}, 
	{ 
		1,
		((0x01 & 0x03) << 8) | 0x32,
		0xFFFF,
		dev_hyvepsureadings_0x32h_1_32_read,
		dev_hyvepsureadings_0x32h_1_32_write,
		dev_hyvepsureadings_0x32h_1_32_init,
		&dev_hyvepsureadings_0x32h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x32h_1_32_properties),
	}, 
	{ 
		2,
		((0x01 & 0x03) << 8) | 0x33,
		0xFFFF,
		dev_hyvepsureadings_0x33h_1_32_read,
		dev_hyvepsureadings_0x33h_1_32_write,
		dev_hyvepsureadings_0x33h_1_32_init,
		&dev_hyvepsureadings_0x33h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x33h_1_32_properties),
	}, 
	{ 
		3,
		((0x01 & 0x03) << 8) | 0x34,
		0xFFFF,
		dev_hyvepsureadings_0x34h_1_32_read,
		dev_hyvepsureadings_0x34h_1_32_write,
		dev_hyvepsureadings_0x34h_1_32_init,
		&dev_hyvepsureadings_0x34h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x34h_1_32_properties),
	}, 
	{ 
		4,
		((0x01 & 0x03) << 8) | 0x35,
		0xFFFF,
		dev_hyvepsureadings_0x35h_1_32_read,
		dev_hyvepsureadings_0x35h_1_32_write,
		dev_hyvepsureadings_0x35h_1_32_init,
		&dev_hyvepsureadings_0x35h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x35h_1_32_properties),
	}, 
	{ 
		5,
		((0x01 & 0x03) << 8) | 0x36,
		0xFFFF,
		dev_hyvepsureadings_0x36h_1_32_read,
		dev_hyvepsureadings_0x36h_1_32_write,
		dev_hyvepsureadings_0x36h_1_32_init,
		&dev_hyvepsureadings_0x36h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x36h_1_32_properties),
	}, 
	{ 
		6,
		((0x01 & 0x03) << 8) | 0x37,
		0xFFFF,
		dev_hyvepsureadings_0x37h_1_32_read,
		dev_hyvepsureadings_0x37h_1_32_write,
		dev_hyvepsureadings_0x37h_1_32_init,
		&dev_hyvepsureadings_0x37h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x37h_1_32_properties),
	}, 
	{ 
		1,
		((0x01 & 0x03) << 8) | 0x38,
		0xffff,
		dev_hyvepsusts_0x38h_1_32_read,
		dev_hyvepsusts_0x38h_1_32_write,
		dev_hyvepsusts_0x38h_1_32_init,
		&dev_hyvepsusts_0x38h_1_32_properties,
		sizeof(dev_hyvepsusts_0x38h_1_32_properties),
	}, 
	{ 
		7,
		((0x01 & 0x03) << 8) | 0x39,
		0xFFFF,
		dev_hyvepsureadings_0x39h_1_32_read,
		dev_hyvepsureadings_0x39h_1_32_write,
		dev_hyvepsureadings_0x39h_1_32_init,
		&dev_hyvepsureadings_0x39h_1_32_properties,
		sizeof(dev_hyvepsureadings_0x39h_1_32_properties),
	}, 
	{ 
		8,
		((0x01 & 0x03) << 8) | 0x3a,
		0xFFFF,
		dev_hyvepsureadings_0x3ah_1_32_read,
		dev_hyvepsureadings_0x3ah_1_32_write,
		dev_hyvepsureadings_0x3ah_1_32_init,
		&dev_hyvepsureadings_0x3ah_1_32_properties,
		sizeof(dev_hyvepsureadings_0x3ah_1_32_properties),
	}, 
	{ 
		9,
		((0x01 & 0x03) << 8) | 0x3b,
		0xFFFF,
		dev_hyvepsureadings_0x3bh_1_32_read,
		dev_hyvepsureadings_0x3bh_1_32_write,
		dev_hyvepsureadings_0x3bh_1_32_init,
		&dev_hyvepsureadings_0x3bh_1_32_properties,
		sizeof(dev_hyvepsureadings_0x3bh_1_32_properties),
	}, 
	{ 
		10,
		((0x01 & 0x03) << 8) | 0x3c,
		0xFFFF,
		dev_hyvepsureadings_0x3ch_1_32_read,
		dev_hyvepsureadings_0x3ch_1_32_write,
		dev_hyvepsureadings_0x3ch_1_32_init,
		&dev_hyvepsureadings_0x3ch_1_32_properties,
		sizeof(dev_hyvepsureadings_0x3ch_1_32_properties),
	}, 
	{ 
		11,
		((0x01 & 0x03) << 8) | 0x3d,
		0xFFFF,
		dev_hyvepsureadings_0x3dh_1_32_read,
		dev_hyvepsureadings_0x3dh_1_32_write,
		dev_hyvepsureadings_0x3dh_1_32_init,
		&dev_hyvepsureadings_0x3dh_1_32_properties,
		sizeof(dev_hyvepsureadings_0x3dh_1_32_properties),
	}, 
	{ 
		12,
		((0x01 & 0x03) << 8) | 0x3e,
		0xFFFF,
		dev_hyvepsureadings_0x3eh_1_32_read,
		dev_hyvepsureadings_0x3eh_1_32_write,
		dev_hyvepsureadings_0x3eh_1_32_init,
		&dev_hyvepsureadings_0x3eh_1_32_properties,
		sizeof(dev_hyvepsureadings_0x3eh_1_32_properties),
	}, 
	{ 
		13,
		((0x01 & 0x03) << 8) | 0x3f,
		0xFFFF,
		dev_hyvepsureadings_0x3fh_1_32_read,
		dev_hyvepsureadings_0x3fh_1_32_write,
		dev_hyvepsureadings_0x3fh_1_32_init,
		&dev_hyvepsureadings_0x3fh_1_32_properties,
		sizeof(dev_hyvepsureadings_0x3fh_1_32_properties),
	}, 
};


/* Total No of Devices */
const int g_total_devices = 2;

long long g_device_platform_tbl[] = 
{
		0xffffffffffffffff,
		0xffffffffffffffff,
};

/**
  * Device Table:
  * -------------	
  *     Field        Size         Purpose 
  *     -------------------------------------------------------- 
  *     1             2           Device Instance 
  *     2             2           Reserved 
  *     3             2           Device ID 
  *     4             2           Device Read Function Pointer 
  *     5             2           Device Write Function Pointer 
  *     6             2           Device Init  Function Pointer 
  *     7             2           Device Properties 
  *     8             2           Device Properties Length 
  **/
device_tbl_t g_device_tbl [] = 
{
	{
		0,
		0xFFFF,
		0xFFFF,
		dev_ast2600_read,
		dev_ast2600_write,
		dev_ast2600_init,
		0,
		0,
	}, 
	{
		0,
		0xFFFF,
		0xffff,
		dev_mb_fru_read,
		dev_mb_fru_write,
		dev_mb_fru_init,
		&dev_mb_fru_properties,
		sizeof(dev_mb_fru_properties),
	}, 
};


/* Error */
const int g_error_code = 0;


/*Devices Init table*/
const phal_hndlr_t g_init_tbl [] = 
{
	dev_hyvepsusts_0x30h_1_32_init,
	dev_hyvepsureadings_0x31h_1_32_init,
	dev_hyvepsureadings_0x32h_1_32_init,
	dev_hyvepsureadings_0x33h_1_32_init,
	dev_hyvepsureadings_0x34h_1_32_init,
	dev_hyvepsureadings_0x35h_1_32_init,
	dev_hyvepsureadings_0x36h_1_32_init,
	dev_hyvepsureadings_0x37h_1_32_init,
	dev_hyvepsusts_0x38h_1_32_init,
	dev_hyvepsureadings_0x39h_1_32_init,
	dev_hyvepsureadings_0x3ah_1_32_init,
	dev_hyvepsureadings_0x3bh_1_32_init,
	dev_hyvepsureadings_0x3ch_1_32_init,
	dev_hyvepsureadings_0x3dh_1_32_init,
	dev_hyvepsureadings_0x3eh_1_32_init,
	dev_hyvepsureadings_0x3fh_1_32_init,


	dev_ast2600_init,
	dev_mb_fru_init,
};

/* *INDENT-ON* */
/*-------------------------------------------------------------*/
/* Functions for device HyvePsuSts [PSU0_Status: dev_hyvepsusts_0x30h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsusts_0x30h_1_32_init  - Init API for the device dev_hyvepsusts_0x30h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsusts_0x30h_1_32_init (hal_t *phal)
{
	dev_hyvepsusts_0x30h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuSts.ddf Line - 7 */
	
/**
 *  dev_hyvepsusts_0x30h_1_32_init_device  - Initialize the device dev_hyvepsusts_0x30h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsusts_0x30h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuSts.ddf Line - 32 */
	{
		UN_USED(phal);
		return 0;
	}
	

/**
 *  dev_hyvepsusts_0x30h_1_32_read  - Read API for the sensor dev_hyvepsusts_0x30h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsusts_0x30h_1_32_read (hal_t *phal)
{
	dev_hyvepsusts_0x30h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsusts_0x30h_1_32_write  - Write API of  the sensor dev_hyvepsusts_0x30h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsusts_0x30h_1_32_write (hal_t *phal)
{
	dev_hyvepsusts_0x30h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsusts_0x30h_1_32_read_device  - Read Function of  the sensor dev_hyvepsusts_0x30h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsusts_0x30h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuSts.ddf Line - 40 */
	{
		HyveMonitor_Get_PSU_Info(0, 0x8, 0x30, 0x1, phal);
		return 0;
	}
	
/**
 *  dev_hyvepsusts_0x30h_1_32_write_device  - Write Function of  the sensor dev_hyvepsusts_0x30h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsusts_0x30h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuSts.ddf Line - 32 */
	{
		UN_USED(phal);
		return 0;
	}
	



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [CURR_PSU0CIN: dev_hyvepsureadings_0x31h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x31h_1_32_init  - Init API for the device dev_hyvepsureadings_0x31h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x31h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x31h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x31h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x31h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x31h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x31h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x31h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x31h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x31h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x31h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x31h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x31h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x31h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x31h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x31h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x31h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x31h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x31h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x31h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x1, 0x31, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > CURR_PSU0CIN_retry ) {
                *phal->pbyte = CURR_PSU0CIN_previous_value;
                ++CURR_PSU0CIN_retry;
            }
        }
        else {
            CURR_PSU0CIN_previous_value = *phal->pbyte;
            CURR_PSU0CIN_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x31h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x31h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x31h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [CURR_PSU0COUT: dev_hyvepsureadings_0x32h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x32h_1_32_init  - Init API for the device dev_hyvepsureadings_0x32h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x32h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x32h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x32h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x32h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x32h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x32h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x32h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x32h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x32h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x32h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x32h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x32h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x32h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x32h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x32h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x32h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x32h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x32h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x32h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x4, 0x32, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > CURR_PSU0COUT_retry ) {
                *phal->pbyte = CURR_PSU0COUT_previous_value;
                ++CURR_PSU0COUT_retry;
            }
        }
        else {
            CURR_PSU0COUT_previous_value = *phal->pbyte;
            CURR_PSU0COUT_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x32h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x32h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x32h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [PWR_PSU0PIN: dev_hyvepsureadings_0x33h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x33h_1_32_init  - Init API for the device dev_hyvepsureadings_0x33h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x33h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x33h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x33h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x33h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x33h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x33h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x33h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x33h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x33h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x33h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x33h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x33h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x33h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x33h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x33h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x33h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x33h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x33h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x33h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x2, 0x33, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > PWR_PSU0PIN_retry ) {
                *phal->pbyte = PWR_PSU0PIN_previous_value;
                ++PWR_PSU0PIN_retry;
            }
        }
        else {
            PWR_PSU0PIN_previous_value = *phal->pbyte;
            PWR_PSU0PIN_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x33h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x33h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x33h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [PWR_PSU0POUT: dev_hyvepsureadings_0x34h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x34h_1_32_init  - Init API for the device dev_hyvepsureadings_0x34h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x34h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x34h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x34h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x34h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x34h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x34h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x34h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x34h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x34h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x34h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x34h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x34h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x34h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x34h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x34h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x34h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x34h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x34h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x34h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x5, 0x34, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > PWR_PSU0POUT_retry ) {
                *phal->pbyte = PWR_PSU0POUT_previous_value;
                ++PWR_PSU0POUT_retry;
            }
        }
        else {
            PWR_PSU0POUT_previous_value = *phal->pbyte;
            PWR_PSU0POUT_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x34h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x34h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x34h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [VOLT_PSU0: dev_hyvepsureadings_0x35h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x35h_1_32_init  - Init API for the device dev_hyvepsureadings_0x35h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x35h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x35h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x35h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x35h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x35h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x35h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x35h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x35h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x35h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x35h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x35h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x35h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x35h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x35h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x35h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x35h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x35h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x35h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x35h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x0, 0x35, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > VOLT_PSU0_retry ) {
                *phal->pbyte = VOLT_PSU0_previous_value;
                ++VOLT_PSU0_retry;
            }
        }
        else {
            VOLT_PSU0_previous_value = *phal->pbyte;
            VOLT_PSU0_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x35h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x35h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x35h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [TEMP_PSU0: dev_hyvepsureadings_0x36h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x36h_1_32_init  - Init API for the device dev_hyvepsureadings_0x36h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x36h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x36h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x36h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x36h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x36h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x36h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x36h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x36h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x36h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x36h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x36h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x36h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x36h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x36h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x36h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x36h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x36h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x36h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x36h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x6, 0x36, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > TEMP_PSU0_retry ) {
                *phal->pbyte = TEMP_PSU0_previous_value;
                ++TEMP_PSU0_retry;
            }
        }
        else {
            TEMP_PSU0_previous_value = *phal->pbyte;
            TEMP_PSU0_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x36h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x36h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x36h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [TACH_PSU0Fan0: dev_hyvepsureadings_0x37h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x37h_1_32_init  - Init API for the device dev_hyvepsureadings_0x37h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x37h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x37h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x37h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x37h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x37h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x37h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x37h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x37h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x37h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x37h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x37h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x37h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x37h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x37h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x37h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x37h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x37h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x37h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x37h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(0, 0x7, 0x37, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > TACH_PSU0Fan0_retry ) {
                *phal->pbyte = TACH_PSU0Fan0_previous_value;
                ++TACH_PSU0Fan0_retry;
            }
        }
        else {
            TACH_PSU0Fan0_previous_value = *phal->pbyte;
            TACH_PSU0Fan0_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x37h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x37h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x37h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePsuSts [PSU1_Status: dev_hyvepsusts_0x38h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsusts_0x38h_1_32_init  - Init API for the device dev_hyvepsusts_0x38h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsusts_0x38h_1_32_init (hal_t *phal)
{
	dev_hyvepsusts_0x38h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuSts.ddf Line - 7 */
	
/**
 *  dev_hyvepsusts_0x38h_1_32_init_device  - Initialize the device dev_hyvepsusts_0x38h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsusts_0x38h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuSts.ddf Line - 32 */
	{
		UN_USED(phal);
		return 0;
	}
	

/**
 *  dev_hyvepsusts_0x38h_1_32_read  - Read API for the sensor dev_hyvepsusts_0x38h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsusts_0x38h_1_32_read (hal_t *phal)
{
	dev_hyvepsusts_0x38h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsusts_0x38h_1_32_write  - Write API of  the sensor dev_hyvepsusts_0x38h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsusts_0x38h_1_32_write (hal_t *phal)
{
	dev_hyvepsusts_0x38h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsusts_0x38h_1_32_read_device  - Read Function of  the sensor dev_hyvepsusts_0x38h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsusts_0x38h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuSts.ddf Line - 40 */
	{
		HyveMonitor_Get_PSU_Info(1, 0x8, 0x38, 0x1, phal);
		return 0;
	}
	
/**
 *  dev_hyvepsusts_0x38h_1_32_write_device  - Write Function of  the sensor dev_hyvepsusts_0x38h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsusts_0x38h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuSts.ddf Line - 32 */
	{
		UN_USED(phal);
		return 0;
	}
	



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [CURR_PSU1CIN: dev_hyvepsureadings_0x39h_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x39h_1_32_init  - Init API for the device dev_hyvepsureadings_0x39h_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x39h_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x39h_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x39h_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x39h_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x39h_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x39h_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x39h_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x39h_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x39h_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x39h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x39h_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x39h_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x39h_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x39h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x39h_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x39h_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x39h_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x39h_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x39h_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x1, 0x39, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > CURR_PSU1CIN_retry ) {
                *phal->pbyte = CURR_PSU1CIN_previous_value;
                ++CURR_PSU1CIN_retry;
            }
        }
        else {
            CURR_PSU1CIN_previous_value = *phal->pbyte;
            CURR_PSU1CIN_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x39h_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x39h_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x39h_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [CURR_PSU1COUT: dev_hyvepsureadings_0x3ah_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x3ah_1_32_init  - Init API for the device dev_hyvepsureadings_0x3ah_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3ah_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x3ah_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x3ah_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x3ah_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x3ah_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x3ah_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x3ah_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3ah_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x3ah_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x3ah_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3ah_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x3ah_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3ah_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x3ah_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3ah_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x3ah_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3ah_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x3ah_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3ah_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x4, 0x3a, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > CURR_PSU1COUT_retry ) {
                *phal->pbyte = CURR_PSU1COUT_previous_value;
                ++CURR_PSU1COUT_retry;
            }
        }
        else {
            CURR_PSU1COUT_previous_value = *phal->pbyte;
            CURR_PSU1COUT_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x3ah_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x3ah_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3ah_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [PWR_PSU1PIN: dev_hyvepsureadings_0x3bh_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x3bh_1_32_init  - Init API for the device dev_hyvepsureadings_0x3bh_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3bh_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x3bh_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x3bh_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x3bh_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x3bh_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x3bh_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x3bh_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3bh_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x3bh_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x3bh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3bh_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x3bh_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3bh_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x3bh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3bh_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x3bh_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3bh_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x3bh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3bh_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x2, 0x3b, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > PWR_PSU1PIN_retry ) {
                *phal->pbyte = PWR_PSU1PIN_previous_value;
                ++PWR_PSU1PIN_retry;
            }
        }
        else {
            PWR_PSU1PIN_previous_value = *phal->pbyte;
            PWR_PSU1PIN_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x3bh_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x3bh_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3bh_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [PWR_PSU1POUT: dev_hyvepsureadings_0x3ch_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x3ch_1_32_init  - Init API for the device dev_hyvepsureadings_0x3ch_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3ch_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x3ch_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x3ch_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x3ch_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x3ch_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x3ch_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x3ch_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3ch_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x3ch_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x3ch_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3ch_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x3ch_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3ch_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x3ch_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3ch_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x3ch_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3ch_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x3ch_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3ch_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x5, 0x3c, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > PWR_PSU1POUT_retry ) {
                *phal->pbyte = PWR_PSU1POUT_previous_value;
                ++PWR_PSU1POUT_retry;
            }
        }
        else {
            PWR_PSU1POUT_previous_value = *phal->pbyte;
            PWR_PSU1POUT_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x3ch_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x3ch_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3ch_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [VOLT_PSU1: dev_hyvepsureadings_0x3dh_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x3dh_1_32_init  - Init API for the device dev_hyvepsureadings_0x3dh_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3dh_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x3dh_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x3dh_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x3dh_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x3dh_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x3dh_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x3dh_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3dh_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x3dh_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x3dh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3dh_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x3dh_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3dh_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x3dh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3dh_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x3dh_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3dh_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x3dh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3dh_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x0, 0x3d, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > VOLT_PSU1_retry ) {
                *phal->pbyte = VOLT_PSU1_previous_value;
                ++VOLT_PSU1_retry;
            }
        }
        else {
            VOLT_PSU1_previous_value = *phal->pbyte;
            VOLT_PSU1_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x3dh_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x3dh_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3dh_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [TEMP_PSU1: dev_hyvepsureadings_0x3eh_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x3eh_1_32_init  - Init API for the device dev_hyvepsureadings_0x3eh_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3eh_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x3eh_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x3eh_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x3eh_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x3eh_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x3eh_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x3eh_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3eh_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x3eh_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x3eh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3eh_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x3eh_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3eh_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x3eh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3eh_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x3eh_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3eh_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x3eh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3eh_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x6, 0x3e, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > TEMP_PSU1_retry ) {
                *phal->pbyte = TEMP_PSU1_previous_value;
                ++TEMP_PSU1_retry;
            }
        }
        else {
            TEMP_PSU1_previous_value = *phal->pbyte;
            TEMP_PSU1_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x3eh_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x3eh_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3eh_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device HyvePSUReadings [TACH_PSU1Fan0: dev_hyvepsureadings_0x3fh_1_32] */
/*-------------------------------------------------------------*/

/**
 *  dev_hyvepsureadings_0x3fh_1_32_init  - Init API for the device dev_hyvepsureadings_0x3fh_1_32
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3fh_1_32_init (hal_t *phal)
{
	dev_hyvepsureadings_0x3fh_1_32_init_device (phal); 
	return 0;
}

/* @source: File - HyvePsuReadings.ddf Line - 0 */
    int dev_hyvepsureadings_0x3fh_1_32_GetNvalue (hal_t* phal) {
        phal->write_len =~phal->write_len;
        phal->write_len &= 0x1f;
        phal->write_len += 0x01;
        return 0;
    }
    
    float dev_hyvepsureadings_0x3fh_1_32_Linearformat (hal_t* phal) {
        int Exp =0;
        float val;
        if((phal->write_len & 0x10) == 0x10) {
            dev_hyvepsureadings_0x3fh_1_32_GetNvalue (phal);
            Exp  = (1 << phal->write_len);
            val = ((double)phal->read_len / Exp);
        }   
        else {
            Exp = (1 << phal->write_len);
            val = phal->read_len * Exp;
        }
        return val; 
    }
    
/**
 *  dev_hyvepsureadings_0x3fh_1_32_init_device  - Initialize the device dev_hyvepsureadings_0x3fh_1_32
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3fh_1_32_init_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    

/**
 *  dev_hyvepsureadings_0x3fh_1_32_read  - Read API for the sensor dev_hyvepsureadings_0x3fh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3fh_1_32_read (hal_t *phal)
{
	dev_hyvepsureadings_0x3fh_1_32_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3fh_1_32_write  - Write API of  the sensor dev_hyvepsureadings_0x3fh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_hyvepsureadings_0x3fh_1_32_write (hal_t *phal)
{
	dev_hyvepsureadings_0x3fh_1_32_write_device  (phal); 
	return 0 ;
}

/**
 *  dev_hyvepsureadings_0x3fh_1_32_read_device  - Read Function of  the sensor dev_hyvepsureadings_0x3fh_1_32
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3fh_1_32_read_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 0 */
    {
        HyveMonitor_Get_PSU_Info(1, 0x7, 0x3f, 0x1, phal);
        if(0 == (*phal->pbyte)) {
            if(3 > TACH_PSU1Fan0_retry ) {
                *phal->pbyte = TACH_PSU1Fan0_previous_value;
                ++TACH_PSU1Fan0_retry;
            }
        }
        else {
            TACH_PSU1Fan0_previous_value = *phal->pbyte;
            TACH_PSU1Fan0_retry = 0;
        }
        return 0;
    }   
    
/**
 *  dev_hyvepsureadings_0x3fh_1_32_write_device  - Write Function of  the sensor dev_hyvepsureadings_0x3fh_1_32
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_hyvepsureadings_0x3fh_1_32_write_device (hal_t *phal) /* @source: File - HyvePsuReadings.ddf Line - 11 */
    {
        UN_USED(phal);
        return 0;
    }    
    



/*-------------------------------------------------------------*/
/* Functions for device Hyve_AST2600 [AST2600: dev_ast2600] */
/*-------------------------------------------------------------*/

/**
 *  dev_ast2600_init  - Init API for the device dev_ast2600
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_ast2600_init (hal_t *phal)
{
	dev_ast2600_init_device (phal); 
	return 0;
}

/**
 *  dev_ast2600_read  - Read API for the device dev_ast2600
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_ast2600_read (hal_t *phal)
{
	dev_ast2600_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_ast2600_write  - Write API of  the device dev_ast2600
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_ast2600_write (hal_t *phal)
{
	dev_ast2600_write_device  (phal); 
	return 0 ;
}

/* @source: File - Hyve_AST2600.ddf Line - 12 */
	
/**
 *  dev_ast2600_init_device  - Initialize the device dev_ast2600
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_ast2600_init_device (hal_t *phal) /* @source: File - Hyve_AST2600.ddf Line - 7 */
	{
		UN_USED(phal);
		return 0;
	}
	
/**
 *  dev_ast2600_read_device  - Read Function of  the device dev_ast2600
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_ast2600_read_device (hal_t *phal) /* @source: File - Hyve_AST2600.ddf Line - 7 */
	{
		UN_USED(phal);
		return 0;
	}
	
/**
 *  dev_ast2600_write_device  - Write Function of  the device dev_ast2600
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_ast2600_write_device (hal_t *phal) /* @source: File - Hyve_AST2600.ddf Line - 7 */
	{
		UN_USED(phal);
		return 0;
	}
	



/*-------------------------------------------------------------*/
/* Functions for device FRU Device [MB_FRU: dev_mb_fru] */
/*-------------------------------------------------------------*/

/**
 *  dev_mb_fru_init  - Init API for the device dev_mb_fru
 *  @return : 0 on  Success
 *    		-1 on Failure
 *  @param  : phal - Pointer to the HAL Info
 **/
int 
dev_mb_fru_init (hal_t *phal)
{
	dev_mb_fru_init_device (phal); 
	return 0;
}

/**
 *  dev_mb_fru_read  - Read API for the device dev_mb_fru
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_mb_fru_read (hal_t *phal)
{
	dev_mb_fru_read_device  (phal); 
	return 0 ;
}

/**
 *  dev_mb_fru_write  - Write API of  the device dev_mb_fru
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int 
dev_mb_fru_write (hal_t *phal)
{
	dev_mb_fru_write_device  (phal); 
	return 0 ;
}

/* @source: File - FRU Device.ddf Line - 19 */
    
    	
    
/**
 *  dev_mb_fru_init_device  - Initialize the device dev_mb_fru
 *   @return : 0 on  Success
 *    		  -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_mb_fru_init_device (hal_t *phal) /* @source: File - FRU Device.ddf Line - 8 */
   {
        UN_USED(phal);
        return 0;
   }
    
/**
 *  dev_mb_fru_read_device  - Read Function of  the device dev_mb_fru
 *   @return : 0 on  Success
 *    		 -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_mb_fru_read_device (hal_t *phal) /* @source: File - FRU Device.ddf Line - 8 */
    {
        UN_USED(phal);
        return 0;
    }
    
/**
 *  dev_mb_fru_write_device  - Write Function of  the device dev_mb_fru
 *   @return : 0 on  Success
 *    		   -1 on Failure
 *   @param  : phal - Pointer to the HAL Info
 **/
int
dev_mb_fru_write_device (hal_t *phal) /* @source: File - FRU Device.ddf Line - 8 */
    {
        UN_USED(phal);
        return 0;
    }
    



/*--------------------- Start of epilog.asm --------------------------*/
int hal_get_total_sensors (void) 
{
      /* provide total number of sensors */ 	
      return g_total_sensors;	
}

device_tbl_t* hal_get_sensor_table_entry (int table_index)
{
      /* return the Sensor table entry */
      return &g_sensor_tbl [table_index];
}

int hal_get_total_devices (void)
{
      /* provide total number of devices  */
      return g_total_devices;
}

device_tbl_t* hal_get_device_table_entry (int table_index)
{
      /* provide device Table entry of the Device  */
      return &g_device_tbl [table_index];
}

phal_hndlr_t hal_get_device_init_entry (int table_index)
{
      /* provide the int table entry of the Device  */
      return g_init_tbl [table_index];
}
/*--------------------- End of epilog.asm --------------------------*/

