/*------------------------------------------------------------*
 * bridgecfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "PMConfig.h"
	#include "Types.h"
	
int
BridgeMgmtSHM_LoadFile(char *File, BridgeMgmtSHM_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->State = IniGetSInt(ini, "BridgeManagementConfiguration", "State", 0x1);

	data->ICMBAddr = IniGetUInt(ini, "BridgeManagementConfiguration", "ICMBAddr", 0x10);

	data->ICMBProxyAddr = IniGetUInt(ini, "BridgeManagementConfiguration", "ICMBProxyAddr", 0x10);

	data->IPMBProxyAddr = IniGetUInt(ini, "BridgeManagementConfiguration", "IPMBProxyAddr", 0x20);

	data->ProxyLUN = IniGetUInt(ini, "BridgeManagementConfiguration", "ProxyLUN", 0x1);

	data->ICMBStats0.RuntCmd = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats0", "RuntCmd", 0);
	data->ICMBStats0.BadCmd = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats0", "BadCmd", 0);
	data->ICMBStats0.SpuriousResp = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats0", "SpuriousResp", 0);

	data->ICMBStats1.Sent = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "Sent", 0);
	data->ICMBStats1.Received = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "Received", 0);
	data->ICMBStats1.OtherAddr = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "OtherAddr", 0);
	data->ICMBStats1.RuntPkt = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "RuntPkt", 0);
	data->ICMBStats1.BadChecksum = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "BadChecksum", 0);
	data->ICMBStats1.UnkType = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "UnkType", 0);
	data->ICMBStats1.NotStart = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "NotStart", 0);
	data->ICMBStats1.Restart = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "Restart", 0);
	data->ICMBStats1.ArbWins = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "ArbWins", 0);
	data->ICMBStats1.ArbLosses = IniGetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "ArbLosses", 0);

	IniCloseFile(ini);
	return 0;
}

int
BridgeMgmtSHM_SaveFile(char *File, BridgeMgmtSHM_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetSInt(ini, "BridgeManagementConfiguration", "State", data->State);

	IniSetUInt(ini, "BridgeManagementConfiguration", "ICMBAddr", data->ICMBAddr);

	IniSetUInt(ini, "BridgeManagementConfiguration", "ICMBProxyAddr", data->ICMBProxyAddr);

	IniSetUInt(ini, "BridgeManagementConfiguration", "IPMBProxyAddr", data->IPMBProxyAddr);

	IniSetUInt(ini, "BridgeManagementConfiguration", "ProxyLUN", data->ProxyLUN);

	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats0", "RuntCmd", data->ICMBStats0.RuntCmd);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats0", "BadCmd", data->ICMBStats0.BadCmd);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats0", "SpuriousResp", data->ICMBStats0.SpuriousResp);

	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "Sent", data->ICMBStats1.Sent);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "Received", data->ICMBStats1.Received);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "OtherAddr", data->ICMBStats1.OtherAddr);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "RuntPkt", data->ICMBStats1.RuntPkt);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "BadChecksum", data->ICMBStats1.BadChecksum);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "UnkType", data->ICMBStats1.UnkType);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "NotStart", data->ICMBStats1.NotStart);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "Restart", data->ICMBStats1.Restart);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "ArbWins", data->ICMBStats1.ArbWins);
	IniSetUInt(ini, "BridgeManagementConfiguration/ICMBStats1", "ArbLosses", data->ICMBStats1.ArbLosses);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

