/*------------------------------------------------------------*
 * dualimagecfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	/* Dual Image Configuration */
	#include "PMConfig.h"
	#include "Types.h"
	#include "featuredef.h"
	#include "PMConfig.h"
	
int
DualImageCfg_LoadFile(char *File, DualImageCfg_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->FwUploadSelector = IniGetUInt(ini, "DualImageCfg", "FwUploadSelector", 0x0);

	IniCloseFile(ini);
	return 0;
}

int
DualImageCfg_SaveFile(char *File, DualImageCfg_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "DualImageCfg", "FwUploadSelector", data->FwUploadSelector);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

