/*------------------------------------------------------------*
 * genericcfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

    /* Generic Configurations */
    
int
Generic_LoadFile(char *File, GENConfig_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->CurrentNoUser = IniGetUInt(ini, "GenericConfig", "CurrentNoUser", 0);

	data->POHCounterReading = IniGetUInt(ini, "GenericConfig", "POHCounterReading", 0);

	data->SELTimeUTCOffset = IniGetUInt(ini, "GenericConfig", "SELTimeUTCOffset", 0);

	data->SDREraseTime = IniGetUInt(ini, "GenericConfig", "SDREraseTime", 0);

	len = strncpy((char*)data->TimeZone, IniGetStr(ini, "GenericConfig", "TimeZone", "GMT+0"), 64);
	if (len >= (int)sizeof(data->TimeZone)) {
		printf("Buffer overflow");
	}

	IniCloseFile(ini);
	return 0;
}

int
Generic_SaveFile(char *File, GENConfig_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "GenericConfig", "CurrentNoUser", data->CurrentNoUser);

	IniSetUInt(ini, "GenericConfig", "POHCounterReading", data->POHCounterReading);

	IniSetUInt(ini, "GenericConfig", "SELTimeUTCOffset", data->SELTimeUTCOffset);

	IniSetUInt(ini, "GenericConfig", "SDREraseTime", data->SDREraseTime);

	IniSetStr(ini, "GenericConfig", "TimeZone", (char*)data->TimeZone);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}


    /*** End of File ***/
    