/*------------------------------------------------------------*
 * loginadtcfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	#include "Types.h"
	#include "PMConfig.h"
	
int
LoginAuditConfig_LoadFile(char *File, LoginAuditConfig_T *pLoginAuditCfg)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	pLoginAuditCfg->WebEventMask = IniGetUInt(ini, "LoginAuditConfiguration", "WebEventMask", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);

	pLoginAuditCfg->IPMIEventMask = IniGetUInt(ini, "LoginAuditConfiguration", "IPMIEventMask", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);

	pLoginAuditCfg->TelnetEventMask = IniGetUInt(ini, "LoginAuditConfiguration", "TelnetEventMask", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);

	pLoginAuditCfg->SSHEventMask = IniGetUInt(ini, "LoginAuditConfiguration", "SSHEventMask", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);

	pLoginAuditCfg->KVMEventMask = IniGetUInt(ini, "LoginAuditConfiguration", "KVMEventMask", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | 0x0);

	IniCloseFile(ini);
	return 0;
}

int
LoginAuditConfig_SaveFile(char *File, LoginAuditConfig_T *pLoginAuditCfg)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "LoginAuditConfiguration", "WebEventMask", pLoginAuditCfg->WebEventMask);

	IniSetUInt(ini, "LoginAuditConfiguration", "IPMIEventMask", pLoginAuditCfg->IPMIEventMask);

	IniSetUInt(ini, "LoginAuditConfiguration", "TelnetEventMask", pLoginAuditCfg->TelnetEventMask);

	IniSetUInt(ini, "LoginAuditConfiguration", "SSHEventMask", pLoginAuditCfg->SSHEventMask);

	IniSetUInt(ini, "LoginAuditConfiguration", "KVMEventMask", pLoginAuditCfg->KVMEventMask);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}


	/* End Login Audit Configuration */
	