/*------------------------------------------------------------*
 * serialcfg.c
 * Warning: This file is generated by PMCP. Any modifications  
 * done on this code will be lost							  
 *------------------------------------------------------------*/
/* *INDENT-OFF* */

/****************************************************************
 ****************************************************************
 **                                                            **
 **    (C)Copyright 2011, American Megatrends Inc.             **
 **                                                            **
 **                 All Rights Reserved.                       **
 **     													   **
 **	    3095 Satellite Boulevard, Building 800, Suite 425,	   **
 **    														   **
 **     Duluth, Georgia 30096, U.S.A Phone-(770)-246-8600.     **
 
 ****************************************************************
 *****************************************************************/

#include <stdio.h>
#include <string.h>
#include "parse-ex.h"
#include "IPMIConf.h"

	/* Serial Configuration Parameters */
  #include "PMConfig.h"
  #include "Types.h"
  
int
SMConfig_LoadFile(char *File, SMConfig_T *data)
{
        int len = 0;
        UN_USED(len);
	INI_HANDLE ini;
	ini=IniLoadFile(File);
	if (ini == NULL)
		return -1;

	data->SetInProgress = IniGetUInt(ini, "SerialCfgParams", "SetInProgress", 0x0);

	data->AuthTypeSupport = IniGetUInt(ini, "SerialCfgParams", "AuthTypeSupport", (0x0 << 5) | (0x1 << 4) | \
			(0x1 << 2) | (0x1 << 1) | 0x1);

	data->AuthTypeEnable.Callback = IniGetUInt(ini, "SerialCfgParams/AuthTypeEnable", "Callback", (0x0 << 5) | (0x1 << 4) | \
			(0x0 << 2) | (0x0 << 1) | 0x1);
	data->AuthTypeEnable.User = IniGetUInt(ini, "SerialCfgParams/AuthTypeEnable", "User", (0x0 << 5) | (0x1 << 4) | \
			(0x0 << 2) | (0x0 << 1) | 0x1);
	data->AuthTypeEnable.Operator = IniGetUInt(ini, "SerialCfgParams/AuthTypeEnable", "Operator", (0x0 << 5) | (0x1 << 4) | \
			(0x0 << 2) | (0x0 << 1) | 0x1);
	data->AuthTypeEnable.Admin = IniGetUInt(ini, "SerialCfgParams/AuthTypeEnable", "Admin", (0x0 << 5) | (0x1 << 4) | \
			(0x0 << 2) | (0x0 << 1) | 0x1);
	data->AuthTypeEnable.oem = IniGetUInt(ini, "SerialCfgParams/AuthTypeEnable", "oem", (0x0 << 5) | (0x1 << 4) | \
			(0x0 << 2) | (0x0 << 1) | 0x1);

	data->ConnectionMode = IniGetUInt(ini, "SerialCfgParams", "ConnectionMode", (0x1 << 7) | (0x1  << 2) | (0x0  << 1) | 0x1);

	data->SessionInactivity = IniGetUInt(ini, "SerialCfgParams", "SessionInactivity", 2);

	data->ChannelCallBackCtrl.CallBackEnable = IniGetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackEnable", (0x0 << 1) | 0x1);
	data->ChannelCallBackCtrl.CBCPnegopt = IniGetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CBCPnegopt", (0x0 << 3) | (0x0 << 2) | \
			      (0x1 << 1) | 0x1);
	data->ChannelCallBackCtrl.CallBackDes1 = IniGetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackDes1", 0);
	data->ChannelCallBackCtrl.CallBackDes2 = IniGetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackDes2", 0);
	data->ChannelCallBackCtrl.CallBackDes3 = IniGetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackDes3", 0);

	data->SessionTermination = IniGetUInt(ini, "SerialCfgParams", "SessionTermination", (0x1 <<1) | 0x1);

	data->IpmiMsgCommSet.FlowCtrl = IniGetUInt(ini, "SerialCfgParams/IpmiMsgCommSet", "FlowCtrl", (0x0 << 6) | (0x0 << 5));
	data->IpmiMsgCommSet.BitRate = IniGetUInt(ini, "SerialCfgParams/IpmiMsgCommSet", "BitRate", 8);

	data->MUXSwitchCtrl.Data1 = IniGetUInt(ini, "SerialCfgParams/MUXSwitchCtrl", "Data1", (0x1 << 6) | (0x1 << 5) | (0x1 << 4) | \
			(0x0 << 3) | (0x1 << 2) | (0x1 << 1) | 0x1);
	data->MUXSwitchCtrl.Data2 = IniGetUInt(ini, "SerialCfgParams/MUXSwitchCtrl", "Data2", (0x1 << 3));

	data->RingTime.RingDuration = IniGetUInt(ini, "SerialCfgParams/RingTime", "RingDuration", 0);
	data->RingTime.RingDeadTime = IniGetUInt(ini, "SerialCfgParams/RingTime", "RingDeadTime", 0);

	len = strncpy((char*)data->ModemInitString[0], IniGetStr(ini, "SerialCfgParams", "ModemInitString/0", ""), 16);
	if (len >= (int)sizeof(data->ModemInitString[0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->ModemInitString[1], IniGetStr(ini, "SerialCfgParams", "ModemInitString/1", ""), 16);
	if (len >= (int)sizeof(data->ModemInitString[1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->ModemInitString[2], IniGetStr(ini, "SerialCfgParams", "ModemInitString/2", ""), 16);
	if (len >= (int)sizeof(data->ModemInitString[2])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->ModemInitString[3], IniGetStr(ini, "SerialCfgParams", "ModemInitString/3", ""), 16);
	if (len >= (int)sizeof(data->ModemInitString[3])) {
		printf("Buffer overflow");
	}

	len = strncpy((char*)data->ModemEscapeSeq, IniGetStr(ini, "SerialCfgParams", "ModemEscapeSeq", ""), 6);
	if (len >= (int)sizeof(data->ModemEscapeSeq)) {
		printf("Buffer overflow");
	}

	len = strncpy((char*)data->ModemHangup, IniGetStr(ini, "SerialCfgParams", "ModemHangup", "ATH"), 9);
	if (len >= (int)sizeof(data->ModemHangup)) {
		printf("Buffer overflow");
	}

	len = strncpy((char*)data->ModemDialCmd, IniGetStr(ini, "SerialCfgParams", "ModemDialCmd", "ATDT"), 9);
	if (len >= (int)sizeof(data->ModemDialCmd)) {
		printf("Buffer overflow");
	}

	data->PageBlockOut = IniGetUInt(ini, "SerialCfgParams", "PageBlockOut", 0);

	len = strncpy((char*)data->CommunityString, IniGetStr(ini, "SerialCfgParams", "CommunityString", ""), 19);
	if (len >= (int)sizeof(data->CommunityString)) {
		printf("Buffer overflow");
	}

	data->TotalAlertDest = IniGetUInt(ini, "SerialCfgParams", "TotalAlertDest", 5);

	data->DestinationInfo[0].DesType = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/0", "DesType", (0x0 << 7) | 0x3);
	data->DestinationInfo[0].AlertAckTimeout = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/0", "AlertAckTimeout", 5);
	data->DestinationInfo[0].Retries = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/0", "Retries", (0 << 4) | 0);
	data->DestinationInfo[0].DesTypeSpecific = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/0", "DesTypeSpecific", (1 << 4) | 0 | (0 << 4) | 0);
	data->DestinationInfo[1].DesType = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/1", "DesType", 0);
	data->DestinationInfo[1].AlertAckTimeout = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/1", "AlertAckTimeout", 0);
	data->DestinationInfo[1].Retries = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/1", "Retries", 0);
	data->DestinationInfo[1].DesTypeSpecific = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/1", "DesTypeSpecific", 0);
	data->DestinationInfo[2].DesType = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/2", "DesType", 0);
	data->DestinationInfo[2].AlertAckTimeout = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/2", "AlertAckTimeout", 0);
	data->DestinationInfo[2].Retries = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/2", "Retries", 0);
	data->DestinationInfo[2].DesTypeSpecific = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/2", "DesTypeSpecific", 0);
	data->DestinationInfo[3].DesType = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/3", "DesType", 0);
	data->DestinationInfo[3].AlertAckTimeout = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/3", "AlertAckTimeout", 0);
	data->DestinationInfo[3].Retries = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/3", "Retries", 0);
	data->DestinationInfo[3].DesTypeSpecific = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/3", "DesTypeSpecific", 0);
	data->DestinationInfo[4].DesType = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/4", "DesType", 0);
	data->DestinationInfo[4].AlertAckTimeout = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/4", "AlertAckTimeout", 0);
	data->DestinationInfo[4].Retries = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/4", "Retries", 0);
	data->DestinationInfo[4].DesTypeSpecific = IniGetUInt(ini, "SerialCfgParams/DestinationInfo/4", "DesTypeSpecific", 0);

	data->CallRetryInterval = IniGetUInt(ini, "SerialCfgParams", "CallRetryInterval", 0);

	data->DestComSet[0].FlowControl = IniGetUInt(ini, "SerialCfgParams/DestComSet/0", "FlowControl", (0x0 << 6) | (0x0 << 4) | (0x0 << 3) | 0x0);
	data->DestComSet[0].BitRate = IniGetUInt(ini, "SerialCfgParams/DestComSet/0", "BitRate", 6);
	data->DestComSet[1].FlowControl = IniGetUInt(ini, "SerialCfgParams/DestComSet/1", "FlowControl", 0);
	data->DestComSet[1].BitRate = IniGetUInt(ini, "SerialCfgParams/DestComSet/1", "BitRate", 0);
	data->DestComSet[2].FlowControl = IniGetUInt(ini, "SerialCfgParams/DestComSet/2", "FlowControl", 0);
	data->DestComSet[2].BitRate = IniGetUInt(ini, "SerialCfgParams/DestComSet/2", "BitRate", 0);
	data->DestComSet[3].FlowControl = IniGetUInt(ini, "SerialCfgParams/DestComSet/3", "FlowControl", 0);
	data->DestComSet[3].BitRate = IniGetUInt(ini, "SerialCfgParams/DestComSet/3", "BitRate", 0);
	data->DestComSet[4].FlowControl = IniGetUInt(ini, "SerialCfgParams/DestComSet/4", "FlowControl", 0);
	data->DestComSet[4].BitRate = IniGetUInt(ini, "SerialCfgParams/DestComSet/4", "BitRate", 0);

	data->TotalDialStr = IniGetUInt(ini, "SerialCfgParams", "TotalDialStr", 5);

	len = strncpy((char*)data->DestDialStrings[0][0], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/0/0", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[0][0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[0][1], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/0/1", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[0][1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[0][2], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/0/2", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[0][2])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[1][0], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/1/0", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[1][0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[1][1], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/1/1", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[1][1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[1][2], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/1/2", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[1][2])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[2][0], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/2/0", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[2][0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[2][1], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/2/1", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[2][1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[2][2], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/2/2", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[2][2])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[3][0], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/3/0", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[3][0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[3][1], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/3/1", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[3][1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[3][2], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/3/2", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[3][2])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[4][0], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/4/0", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[4][0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[4][1], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/4/1", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[4][1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->DestDialStrings[4][2], IniGetStr(ini, "SerialCfgParams", "DestDialStrings/4/2", ""), 16);
	if (len >= (int)sizeof(data->DestDialStrings[4][2])) {
		printf("Buffer overflow");
	}

	data->TotalDestIP = IniGetUInt(ini, "SerialCfgParams", "TotalDestIP", 5);

	data->DestAddr[0].ip[0] = IniGetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/0", 0);
	data->DestAddr[0].ip[1] = IniGetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/1", 0);
	data->DestAddr[0].ip[2] = IniGetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/2", 0);
	data->DestAddr[0].ip[3] = IniGetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/3", 0);
	data->DestAddr[1].ip[0] = IniGetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/0", 0);
	data->DestAddr[1].ip[1] = IniGetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/1", 0);
	data->DestAddr[1].ip[2] = IniGetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/2", 0);
	data->DestAddr[1].ip[3] = IniGetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/3", 0);
	data->DestAddr[2].ip[0] = IniGetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/0", 0);
	data->DestAddr[2].ip[1] = IniGetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/1", 0);
	data->DestAddr[2].ip[2] = IniGetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/2", 0);
	data->DestAddr[2].ip[3] = IniGetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/3", 0);
	data->DestAddr[3].ip[0] = IniGetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/0", 0);
	data->DestAddr[3].ip[1] = IniGetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/1", 0);
	data->DestAddr[3].ip[2] = IniGetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/2", 0);
	data->DestAddr[3].ip[3] = IniGetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/3", 0);
	data->DestAddr[4].ip[0] = IniGetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/0", 0);
	data->DestAddr[4].ip[1] = IniGetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/1", 0);
	data->DestAddr[4].ip[2] = IniGetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/2", 0);
	data->DestAddr[4].ip[3] = IniGetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/3", 0);

	data->TotalTAPAcc = IniGetUInt(ini, "SerialCfgParams", "TotalTAPAcc", 5);

	data->TAPAccountSelector[0] = IniGetUInt(ini, "SerialCfgParams", "TAPAccountSelector/0", (0 << 4) | 0);
	data->TAPAccountSelector[1] = IniGetUInt(ini, "SerialCfgParams", "TAPAccountSelector/1", (0 << 4) | 0);
	data->TAPAccountSelector[2] = IniGetUInt(ini, "SerialCfgParams", "TAPAccountSelector/2", (0 << 4) | 0);

	len = strncpy((char*)data->TAPPasswd[0], IniGetStr(ini, "SerialCfgParams", "TAPPasswd/0", ""), 8);
	if (len >= (int)sizeof(data->TAPPasswd[0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->TAPPasswd[1], IniGetStr(ini, "SerialCfgParams", "TAPPasswd/1", ""), 8);
	if (len >= (int)sizeof(data->TAPPasswd[1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->TAPPasswd[2], IniGetStr(ini, "SerialCfgParams", "TAPPasswd/2", ""), 8);
	if (len >= (int)sizeof(data->TAPPasswd[2])) {
		printf("Buffer overflow");
	}

	len = strncpy((char*)data->TAPPagerIDStrings[0], IniGetStr(ini, "SerialCfgParams", "TAPPagerIDStrings/0", ""), 14);
	if (len >= (int)sizeof(data->TAPPagerIDStrings[0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->TAPPagerIDStrings[1], IniGetStr(ini, "SerialCfgParams", "TAPPagerIDStrings/1", ""), 14);
	if (len >= (int)sizeof(data->TAPPagerIDStrings[1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->TAPPagerIDStrings[2], IniGetStr(ini, "SerialCfgParams", "TAPPagerIDStrings/2", ""), 14);
	if (len >= (int)sizeof(data->TAPPagerIDStrings[2])) {
		printf("Buffer overflow");
	}

	data->TAPServiceSettings[0].TAPConfirmation = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TAPConfirmation", 0x0);
	len = strncpy((char*)data->TAPServiceSettings[0].TAPServiceTypeChars, IniGetStr(ini, "SerialCfgParams/TAPServiceSettings/0", "TAPServiceTypeChars", ""), 3);
	if (len >= (int)sizeof(data->TAPServiceSettings[0].TAPServiceTypeChars)) {
		printf("Buffer overflow");
	}
	data->TAPServiceSettings[0].TAPCtrlESCMask = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TAPCtrlESCMask", 0xffff);
	data->TAPServiceSettings[0].TimeOutParam1 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TimeOutParam1", (0 << 4) | 0);
	data->TAPServiceSettings[0].TimeOutParam2 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TimeOutParam2", (0 << 4) | 0);
	data->TAPServiceSettings[0].TimeOutParam3 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TimeOutParam3", (0 << 4) | 0);
	data->TAPServiceSettings[0].RetryParam1 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "RetryParam1", (0 << 4) | 0);
	data->TAPServiceSettings[0].RetryParam2 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "RetryParam2", (0 << 4) | 0);
	data->TAPServiceSettings[1].TAPConfirmation = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TAPConfirmation", 0);
	len = strncpy((char*)data->TAPServiceSettings[1].TAPServiceTypeChars, IniGetStr(ini, "SerialCfgParams/TAPServiceSettings/1", "TAPServiceTypeChars", ""), 3);
	if (len >= (int)sizeof(data->TAPServiceSettings[1].TAPServiceTypeChars)) {
		printf("Buffer overflow");
	}
	data->TAPServiceSettings[1].TAPCtrlESCMask = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TAPCtrlESCMask", 0);
	data->TAPServiceSettings[1].TimeOutParam1 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TimeOutParam1", 0);
	data->TAPServiceSettings[1].TimeOutParam2 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TimeOutParam2", 0);
	data->TAPServiceSettings[1].TimeOutParam3 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TimeOutParam3", 0);
	data->TAPServiceSettings[1].RetryParam1 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "RetryParam1", 0);
	data->TAPServiceSettings[1].RetryParam2 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "RetryParam2", 0);
	data->TAPServiceSettings[2].TAPConfirmation = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TAPConfirmation", 0);
	len = strncpy((char*)data->TAPServiceSettings[2].TAPServiceTypeChars, IniGetStr(ini, "SerialCfgParams/TAPServiceSettings/2", "TAPServiceTypeChars", ""), 3);
	if (len >= (int)sizeof(data->TAPServiceSettings[2].TAPServiceTypeChars)) {
		printf("Buffer overflow");
	}
	data->TAPServiceSettings[2].TAPCtrlESCMask = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TAPCtrlESCMask", 0);
	data->TAPServiceSettings[2].TimeOutParam1 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TimeOutParam1", 0);
	data->TAPServiceSettings[2].TimeOutParam2 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TimeOutParam2", 0);
	data->TAPServiceSettings[2].TimeOutParam3 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TimeOutParam3", 0);
	data->TAPServiceSettings[2].RetryParam1 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "RetryParam1", 0);
	data->TAPServiceSettings[2].RetryParam2 = IniGetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "RetryParam2", 0);

	data->Termconfig.Data1 = IniGetUInt(ini, "SerialCfgParams/Termconfig", "Data1", (0x0 << 6) | (0x0 << 5) |  \
			   (0x0 << 2) | (0x0 << 1) | 0x0);
	data->Termconfig.Data2 = IniGetUInt(ini, "SerialCfgParams/Termconfig", "Data2", (0x0 << 4) | 0x1);

	data->PPPProtocolOptions.SnoopControl = IniGetUInt(ini, "SerialCfgParams/PPPProtocolOptions", "SnoopControl", (0x0 << 1) | 0x0);
	data->PPPProtocolOptions.NegControl = IniGetUInt(ini, "SerialCfgParams/PPPProtocolOptions", "NegControl", (0x0 << 4) | (0x0 << 2) | (0x0 << 1) | (0x0 << 0));
	data->PPPProtocolOptions.NegConfig = IniGetUInt(ini, "SerialCfgParams/PPPProtocolOptions", "NegConfig", (0x0 << 3) | (0x0 << 2) | (0x0 << 1) | (0x0 << 0));

	data->PPPPrimaryRMCPPort = IniGetUInt(ini, "SerialCfgParams", "PPPPrimaryRMCPPort", 0);

	data->PPPSecondaryRMCPPort = IniGetUInt(ini, "SerialCfgParams", "PPPSecondaryRMCPPort", 0);

	data->PPPLinkAuth = IniGetUInt(ini, "SerialCfgParams", "PPPLinkAuth", 0x0);

	len = strncpy((char*)data->CHAPName, IniGetStr(ini, "SerialCfgParams", "CHAPName", ""), 16);
	if (len >= (int)sizeof(data->CHAPName)) {
		printf("Buffer overflow");
	}

	data->PPPACCM.ReceiveACCM = IniGetUInt(ini, "SerialCfgParams/PPPACCM", "ReceiveACCM", 0);
	data->PPPACCM.TransmitACCM = IniGetUInt(ini, "SerialCfgParams/PPPACCM", "TransmitACCM", 0);

	data->PPPSnoopACCM.ReceiveACCM = IniGetUInt(ini, "SerialCfgParams/PPPSnoopACCM", "ReceiveACCM", 0);

	data->TotalPPPAcc = IniGetUInt(ini, "SerialCfgParams", "TotalPPPAcc", 3);

	data->PPPAccDialStrSel[0] = IniGetUInt(ini, "SerialCfgParams", "PPPAccDialStrSel/0", 0);
	data->PPPAccDialStrSel[1] = IniGetUInt(ini, "SerialCfgParams", "PPPAccDialStrSel/1", 0);
	data->PPPAccDialStrSel[2] = IniGetUInt(ini, "SerialCfgParams", "PPPAccDialStrSel/2", 0);

	data->PPPAccIPAddress[0][0] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/0", 0);
	data->PPPAccIPAddress[0][1] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/1", 0);
	data->PPPAccIPAddress[0][2] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/2", 0);
	data->PPPAccIPAddress[0][3] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/3", 0);
	data->PPPAccIPAddress[1][0] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/0", 0);
	data->PPPAccIPAddress[1][1] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/1", 0);
	data->PPPAccIPAddress[1][2] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/2", 0);
	data->PPPAccIPAddress[1][3] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/3", 0);
	data->PPPAccIPAddress[2][0] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/0", 0);
	data->PPPAccIPAddress[2][1] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/1", 0);
	data->PPPAccIPAddress[2][2] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/2", 0);
	data->PPPAccIPAddress[2][3] = IniGetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/3", 0);

	len = strncpy((char*)data->PPPAccUserNames[0], IniGetStr(ini, "SerialCfgParams", "PPPAccUserNames/0", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserNames[0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->PPPAccUserNames[1], IniGetStr(ini, "SerialCfgParams", "PPPAccUserNames/1", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserNames[1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->PPPAccUserNames[2], IniGetStr(ini, "SerialCfgParams", "PPPAccUserNames/2", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserNames[2])) {
		printf("Buffer overflow");
	}

	len = strncpy((char*)data->PPPAccUserDomain[0], IniGetStr(ini, "SerialCfgParams", "PPPAccUserDomain/0", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserDomain[0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->PPPAccUserDomain[1], IniGetStr(ini, "SerialCfgParams", "PPPAccUserDomain/1", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserDomain[1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->PPPAccUserDomain[2], IniGetStr(ini, "SerialCfgParams", "PPPAccUserDomain/2", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserDomain[2])) {
		printf("Buffer overflow");
	}

	len = strncpy((char*)data->PPPAccUserPasswd[0], IniGetStr(ini, "SerialCfgParams", "PPPAccUserPasswd/0", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserPasswd[0])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->PPPAccUserPasswd[1], IniGetStr(ini, "SerialCfgParams", "PPPAccUserPasswd/1", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserPasswd[1])) {
		printf("Buffer overflow");
	}
	len = strncpy((char*)data->PPPAccUserPasswd[2], IniGetStr(ini, "SerialCfgParams", "PPPAccUserPasswd/2", ""), 17);
	if (len >= (int)sizeof(data->PPPAccUserPasswd[2])) {
		printf("Buffer overflow");
	}

	data->PPPAccAuthSettings[0] = IniGetUInt(ini, "SerialCfgParams", "PPPAccAuthSettings/0", 0x0);
	data->PPPAccAuthSettings[1] = IniGetUInt(ini, "SerialCfgParams", "PPPAccAuthSettings/1", 0x0);
	data->PPPAccAuthSettings[2] = IniGetUInt(ini, "SerialCfgParams", "PPPAccAuthSettings/2", 0x0);

	data->PPPAccConnHoldTimes[0] = IniGetUInt(ini, "SerialCfgParams", "PPPAccConnHoldTimes/0", 0);
	data->PPPAccConnHoldTimes[1] = IniGetUInt(ini, "SerialCfgParams", "PPPAccConnHoldTimes/1", 0);
	data->PPPAccConnHoldTimes[2] = IniGetUInt(ini, "SerialCfgParams", "PPPAccConnHoldTimes/2", 0);

	data->PPPUDPProxyIPHeadData.SrcIPAddress[0] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/0", 0);
	data->PPPUDPProxyIPHeadData.SrcIPAddress[1] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/1", 0);
	data->PPPUDPProxyIPHeadData.SrcIPAddress[2] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/2", 0);
	data->PPPUDPProxyIPHeadData.SrcIPAddress[3] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/3", 0);
	data->PPPUDPProxyIPHeadData.DestIPAddress[0] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/0", 0);
	data->PPPUDPProxyIPHeadData.DestIPAddress[1] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/1", 0);
	data->PPPUDPProxyIPHeadData.DestIPAddress[2] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/2", 0);
	data->PPPUDPProxyIPHeadData.DestIPAddress[3] = IniGetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/3", 0);

	data->PPPUDPProxyTransmitBuffSize = IniGetUInt(ini, "SerialCfgParams", "PPPUDPProxyTransmitBuffSize", 0);

	data->PPPUDPProxyReceiveBuffSize = IniGetUInt(ini, "SerialCfgParams", "PPPUDPProxyReceiveBuffSize", 0);

	data->PPPRemoteConsoleIPAdd[0] = IniGetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/0", 0);
	data->PPPRemoteConsoleIPAdd[1] = IniGetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/1", 0);
	data->PPPRemoteConsoleIPAdd[2] = IniGetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/2", 0);
	data->PPPRemoteConsoleIPAdd[3] = IniGetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/3", 0);

	data->BadPasswd.GenEvent = IniGetUInt(ini, "SerialCfgParams/BadPasswd", "GenEvent", 1);
	data->BadPasswd.ThreshNum = IniGetUInt(ini, "SerialCfgParams/BadPasswd", "ThreshNum", 0);
	data->BadPasswd.ResetInterval = IniGetUInt(ini, "SerialCfgParams/BadPasswd", "ResetInterval", 0);
	data->BadPasswd.LockoutInterval = IniGetUInt(ini, "SerialCfgParams/BadPasswd", "LockoutInterval", 0);

	IniCloseFile(ini);
	return 0;
}

int
SMConfig_SaveFile(char *File, SMConfig_T *data)
{
	static INI_HANDLE ini = NULL;
	if(ini == NULL)
	{
		ini=IniLoadFile(File);
		if (ini == NULL)
			return -1;
	}

	IniSetUInt(ini, "SerialCfgParams", "SetInProgress", data->SetInProgress);

	IniSetUInt(ini, "SerialCfgParams", "AuthTypeSupport", data->AuthTypeSupport);

	IniSetUInt(ini, "SerialCfgParams/AuthTypeEnable", "Callback", data->AuthTypeEnable.Callback);
	IniSetUInt(ini, "SerialCfgParams/AuthTypeEnable", "User", data->AuthTypeEnable.User);
	IniSetUInt(ini, "SerialCfgParams/AuthTypeEnable", "Operator", data->AuthTypeEnable.Operator);
	IniSetUInt(ini, "SerialCfgParams/AuthTypeEnable", "Admin", data->AuthTypeEnable.Admin);
	IniSetUInt(ini, "SerialCfgParams/AuthTypeEnable", "oem", data->AuthTypeEnable.oem);

	IniSetUInt(ini, "SerialCfgParams", "ConnectionMode", data->ConnectionMode);

	IniSetUInt(ini, "SerialCfgParams", "SessionInactivity", data->SessionInactivity);

	IniSetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackEnable", data->ChannelCallBackCtrl.CallBackEnable);
	IniSetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CBCPnegopt", data->ChannelCallBackCtrl.CBCPnegopt);
	IniSetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackDes1", data->ChannelCallBackCtrl.CallBackDes1);
	IniSetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackDes2", data->ChannelCallBackCtrl.CallBackDes2);
	IniSetUInt(ini, "SerialCfgParams/ChannelCallBackCtrl", "CallBackDes3", data->ChannelCallBackCtrl.CallBackDes3);

	IniSetUInt(ini, "SerialCfgParams", "SessionTermination", data->SessionTermination);

	IniSetUInt(ini, "SerialCfgParams/IpmiMsgCommSet", "FlowCtrl", data->IpmiMsgCommSet.FlowCtrl);
	IniSetUInt(ini, "SerialCfgParams/IpmiMsgCommSet", "BitRate", data->IpmiMsgCommSet.BitRate);

	IniSetUInt(ini, "SerialCfgParams/MUXSwitchCtrl", "Data1", data->MUXSwitchCtrl.Data1);
	IniSetUInt(ini, "SerialCfgParams/MUXSwitchCtrl", "Data2", data->MUXSwitchCtrl.Data2);

	IniSetUInt(ini, "SerialCfgParams/RingTime", "RingDuration", data->RingTime.RingDuration);
	IniSetUInt(ini, "SerialCfgParams/RingTime", "RingDeadTime", data->RingTime.RingDeadTime);

	IniSetStr(ini, "SerialCfgParams", "ModemInitString/0", (char*)data->ModemInitString[0]);
	IniSetStr(ini, "SerialCfgParams", "ModemInitString/1", (char*)data->ModemInitString[1]);
	IniSetStr(ini, "SerialCfgParams", "ModemInitString/2", (char*)data->ModemInitString[2]);
	IniSetStr(ini, "SerialCfgParams", "ModemInitString/3", (char*)data->ModemInitString[3]);

	IniSetStr(ini, "SerialCfgParams", "ModemEscapeSeq", (char*)data->ModemEscapeSeq);

	IniSetStr(ini, "SerialCfgParams", "ModemHangup", (char*)data->ModemHangup);

	IniSetStr(ini, "SerialCfgParams", "ModemDialCmd", (char*)data->ModemDialCmd);

	IniSetUInt(ini, "SerialCfgParams", "PageBlockOut", data->PageBlockOut);

	IniSetStr(ini, "SerialCfgParams", "CommunityString", (char*)data->CommunityString);

	IniSetUInt(ini, "SerialCfgParams", "TotalAlertDest", data->TotalAlertDest);

	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/0", "DesType", data->DestinationInfo[0].DesType);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/0", "AlertAckTimeout", data->DestinationInfo[0].AlertAckTimeout);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/0", "Retries", data->DestinationInfo[0].Retries);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/0", "DesTypeSpecific", data->DestinationInfo[0].DesTypeSpecific);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/1", "DesType", data->DestinationInfo[1].DesType);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/1", "AlertAckTimeout", data->DestinationInfo[1].AlertAckTimeout);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/1", "Retries", data->DestinationInfo[1].Retries);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/1", "DesTypeSpecific", data->DestinationInfo[1].DesTypeSpecific);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/2", "DesType", data->DestinationInfo[2].DesType);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/2", "AlertAckTimeout", data->DestinationInfo[2].AlertAckTimeout);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/2", "Retries", data->DestinationInfo[2].Retries);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/2", "DesTypeSpecific", data->DestinationInfo[2].DesTypeSpecific);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/3", "DesType", data->DestinationInfo[3].DesType);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/3", "AlertAckTimeout", data->DestinationInfo[3].AlertAckTimeout);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/3", "Retries", data->DestinationInfo[3].Retries);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/3", "DesTypeSpecific", data->DestinationInfo[3].DesTypeSpecific);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/4", "DesType", data->DestinationInfo[4].DesType);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/4", "AlertAckTimeout", data->DestinationInfo[4].AlertAckTimeout);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/4", "Retries", data->DestinationInfo[4].Retries);
	IniSetUInt(ini, "SerialCfgParams/DestinationInfo/4", "DesTypeSpecific", data->DestinationInfo[4].DesTypeSpecific);

	IniSetUInt(ini, "SerialCfgParams", "CallRetryInterval", data->CallRetryInterval);

	IniSetUInt(ini, "SerialCfgParams/DestComSet/0", "FlowControl", data->DestComSet[0].FlowControl);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/0", "BitRate", data->DestComSet[0].BitRate);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/1", "FlowControl", data->DestComSet[1].FlowControl);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/1", "BitRate", data->DestComSet[1].BitRate);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/2", "FlowControl", data->DestComSet[2].FlowControl);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/2", "BitRate", data->DestComSet[2].BitRate);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/3", "FlowControl", data->DestComSet[3].FlowControl);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/3", "BitRate", data->DestComSet[3].BitRate);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/4", "FlowControl", data->DestComSet[4].FlowControl);
	IniSetUInt(ini, "SerialCfgParams/DestComSet/4", "BitRate", data->DestComSet[4].BitRate);

	IniSetUInt(ini, "SerialCfgParams", "TotalDialStr", data->TotalDialStr);

	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/0/0", (char*)data->DestDialStrings[0][0]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/0/1", (char*)data->DestDialStrings[0][1]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/0/2", (char*)data->DestDialStrings[0][2]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/1/0", (char*)data->DestDialStrings[1][0]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/1/1", (char*)data->DestDialStrings[1][1]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/1/2", (char*)data->DestDialStrings[1][2]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/2/0", (char*)data->DestDialStrings[2][0]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/2/1", (char*)data->DestDialStrings[2][1]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/2/2", (char*)data->DestDialStrings[2][2]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/3/0", (char*)data->DestDialStrings[3][0]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/3/1", (char*)data->DestDialStrings[3][1]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/3/2", (char*)data->DestDialStrings[3][2]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/4/0", (char*)data->DestDialStrings[4][0]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/4/1", (char*)data->DestDialStrings[4][1]);
	IniSetStr(ini, "SerialCfgParams", "DestDialStrings/4/2", (char*)data->DestDialStrings[4][2]);

	IniSetUInt(ini, "SerialCfgParams", "TotalDestIP", data->TotalDestIP);

	IniSetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/0", data->DestAddr[0].ip[0]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/1", data->DestAddr[0].ip[1]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/2", data->DestAddr[0].ip[2]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/0", "ip/3", data->DestAddr[0].ip[3]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/0", data->DestAddr[1].ip[0]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/1", data->DestAddr[1].ip[1]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/2", data->DestAddr[1].ip[2]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/1", "ip/3", data->DestAddr[1].ip[3]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/0", data->DestAddr[2].ip[0]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/1", data->DestAddr[2].ip[1]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/2", data->DestAddr[2].ip[2]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/2", "ip/3", data->DestAddr[2].ip[3]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/0", data->DestAddr[3].ip[0]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/1", data->DestAddr[3].ip[1]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/2", data->DestAddr[3].ip[2]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/3", "ip/3", data->DestAddr[3].ip[3]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/0", data->DestAddr[4].ip[0]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/1", data->DestAddr[4].ip[1]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/2", data->DestAddr[4].ip[2]);
	IniSetUInt(ini, "SerialCfgParams/DestAddr/4", "ip/3", data->DestAddr[4].ip[3]);

	IniSetUInt(ini, "SerialCfgParams", "TotalTAPAcc", data->TotalTAPAcc);

	IniSetUInt(ini, "SerialCfgParams", "TAPAccountSelector/0", data->TAPAccountSelector[0]);
	IniSetUInt(ini, "SerialCfgParams", "TAPAccountSelector/1", data->TAPAccountSelector[1]);
	IniSetUInt(ini, "SerialCfgParams", "TAPAccountSelector/2", data->TAPAccountSelector[2]);

	IniSetStr(ini, "SerialCfgParams", "TAPPasswd/0", (char*)data->TAPPasswd[0]);
	IniSetStr(ini, "SerialCfgParams", "TAPPasswd/1", (char*)data->TAPPasswd[1]);
	IniSetStr(ini, "SerialCfgParams", "TAPPasswd/2", (char*)data->TAPPasswd[2]);

	IniSetStr(ini, "SerialCfgParams", "TAPPagerIDStrings/0", (char*)data->TAPPagerIDStrings[0]);
	IniSetStr(ini, "SerialCfgParams", "TAPPagerIDStrings/1", (char*)data->TAPPagerIDStrings[1]);
	IniSetStr(ini, "SerialCfgParams", "TAPPagerIDStrings/2", (char*)data->TAPPagerIDStrings[2]);

	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TAPConfirmation", data->TAPServiceSettings[0].TAPConfirmation);
	IniSetStr(ini, "SerialCfgParams/TAPServiceSettings/0", "TAPServiceTypeChars", (char*)data->TAPServiceSettings[0].TAPServiceTypeChars);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TAPCtrlESCMask", data->TAPServiceSettings[0].TAPCtrlESCMask);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TimeOutParam1", data->TAPServiceSettings[0].TimeOutParam1);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TimeOutParam2", data->TAPServiceSettings[0].TimeOutParam2);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "TimeOutParam3", data->TAPServiceSettings[0].TimeOutParam3);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "RetryParam1", data->TAPServiceSettings[0].RetryParam1);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/0", "RetryParam2", data->TAPServiceSettings[0].RetryParam2);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TAPConfirmation", data->TAPServiceSettings[1].TAPConfirmation);
	IniSetStr(ini, "SerialCfgParams/TAPServiceSettings/1", "TAPServiceTypeChars", (char*)data->TAPServiceSettings[1].TAPServiceTypeChars);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TAPCtrlESCMask", data->TAPServiceSettings[1].TAPCtrlESCMask);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TimeOutParam1", data->TAPServiceSettings[1].TimeOutParam1);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TimeOutParam2", data->TAPServiceSettings[1].TimeOutParam2);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "TimeOutParam3", data->TAPServiceSettings[1].TimeOutParam3);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "RetryParam1", data->TAPServiceSettings[1].RetryParam1);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/1", "RetryParam2", data->TAPServiceSettings[1].RetryParam2);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TAPConfirmation", data->TAPServiceSettings[2].TAPConfirmation);
	IniSetStr(ini, "SerialCfgParams/TAPServiceSettings/2", "TAPServiceTypeChars", (char*)data->TAPServiceSettings[2].TAPServiceTypeChars);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TAPCtrlESCMask", data->TAPServiceSettings[2].TAPCtrlESCMask);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TimeOutParam1", data->TAPServiceSettings[2].TimeOutParam1);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TimeOutParam2", data->TAPServiceSettings[2].TimeOutParam2);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "TimeOutParam3", data->TAPServiceSettings[2].TimeOutParam3);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "RetryParam1", data->TAPServiceSettings[2].RetryParam1);
	IniSetUInt(ini, "SerialCfgParams/TAPServiceSettings/2", "RetryParam2", data->TAPServiceSettings[2].RetryParam2);

	IniSetUInt(ini, "SerialCfgParams/Termconfig", "Data1", data->Termconfig.Data1);
	IniSetUInt(ini, "SerialCfgParams/Termconfig", "Data2", data->Termconfig.Data2);

	IniSetUInt(ini, "SerialCfgParams/PPPProtocolOptions", "SnoopControl", data->PPPProtocolOptions.SnoopControl);
	IniSetUInt(ini, "SerialCfgParams/PPPProtocolOptions", "NegControl", data->PPPProtocolOptions.NegControl);
	IniSetUInt(ini, "SerialCfgParams/PPPProtocolOptions", "NegConfig", data->PPPProtocolOptions.NegConfig);

	IniSetUInt(ini, "SerialCfgParams", "PPPPrimaryRMCPPort", data->PPPPrimaryRMCPPort);

	IniSetUInt(ini, "SerialCfgParams", "PPPSecondaryRMCPPort", data->PPPSecondaryRMCPPort);

	IniSetUInt(ini, "SerialCfgParams", "PPPLinkAuth", data->PPPLinkAuth);

	IniSetStr(ini, "SerialCfgParams", "CHAPName", (char*)data->CHAPName);

	IniSetUInt(ini, "SerialCfgParams/PPPACCM", "ReceiveACCM", data->PPPACCM.ReceiveACCM);
	IniSetUInt(ini, "SerialCfgParams/PPPACCM", "TransmitACCM", data->PPPACCM.TransmitACCM);

	IniSetUInt(ini, "SerialCfgParams/PPPSnoopACCM", "ReceiveACCM", data->PPPSnoopACCM.ReceiveACCM);

	IniSetUInt(ini, "SerialCfgParams", "TotalPPPAcc", data->TotalPPPAcc);

	IniSetUInt(ini, "SerialCfgParams", "PPPAccDialStrSel/0", data->PPPAccDialStrSel[0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccDialStrSel/1", data->PPPAccDialStrSel[1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccDialStrSel/2", data->PPPAccDialStrSel[2]);

	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/0", data->PPPAccIPAddress[0][0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/1", data->PPPAccIPAddress[0][1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/2", data->PPPAccIPAddress[0][2]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/0/3", data->PPPAccIPAddress[0][3]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/0", data->PPPAccIPAddress[1][0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/1", data->PPPAccIPAddress[1][1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/2", data->PPPAccIPAddress[1][2]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/1/3", data->PPPAccIPAddress[1][3]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/0", data->PPPAccIPAddress[2][0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/1", data->PPPAccIPAddress[2][1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/2", data->PPPAccIPAddress[2][2]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccIPAddress/2/3", data->PPPAccIPAddress[2][3]);

	IniSetStr(ini, "SerialCfgParams", "PPPAccUserNames/0", (char*)data->PPPAccUserNames[0]);
	IniSetStr(ini, "SerialCfgParams", "PPPAccUserNames/1", (char*)data->PPPAccUserNames[1]);
	IniSetStr(ini, "SerialCfgParams", "PPPAccUserNames/2", (char*)data->PPPAccUserNames[2]);

	IniSetStr(ini, "SerialCfgParams", "PPPAccUserDomain/0", (char*)data->PPPAccUserDomain[0]);
	IniSetStr(ini, "SerialCfgParams", "PPPAccUserDomain/1", (char*)data->PPPAccUserDomain[1]);
	IniSetStr(ini, "SerialCfgParams", "PPPAccUserDomain/2", (char*)data->PPPAccUserDomain[2]);

	IniSetStr(ini, "SerialCfgParams", "PPPAccUserPasswd/0", (char*)data->PPPAccUserPasswd[0]);
	IniSetStr(ini, "SerialCfgParams", "PPPAccUserPasswd/1", (char*)data->PPPAccUserPasswd[1]);
	IniSetStr(ini, "SerialCfgParams", "PPPAccUserPasswd/2", (char*)data->PPPAccUserPasswd[2]);

	IniSetUInt(ini, "SerialCfgParams", "PPPAccAuthSettings/0", data->PPPAccAuthSettings[0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccAuthSettings/1", data->PPPAccAuthSettings[1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccAuthSettings/2", data->PPPAccAuthSettings[2]);

	IniSetUInt(ini, "SerialCfgParams", "PPPAccConnHoldTimes/0", data->PPPAccConnHoldTimes[0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccConnHoldTimes/1", data->PPPAccConnHoldTimes[1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPAccConnHoldTimes/2", data->PPPAccConnHoldTimes[2]);

	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/0", data->PPPUDPProxyIPHeadData.SrcIPAddress[0]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/1", data->PPPUDPProxyIPHeadData.SrcIPAddress[1]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/2", data->PPPUDPProxyIPHeadData.SrcIPAddress[2]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "SrcIPAddress/3", data->PPPUDPProxyIPHeadData.SrcIPAddress[3]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/0", data->PPPUDPProxyIPHeadData.DestIPAddress[0]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/1", data->PPPUDPProxyIPHeadData.DestIPAddress[1]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/2", data->PPPUDPProxyIPHeadData.DestIPAddress[2]);
	IniSetUInt(ini, "SerialCfgParams/PPPUDPProxyIPHeadData", "DestIPAddress/3", data->PPPUDPProxyIPHeadData.DestIPAddress[3]);

	IniSetUInt(ini, "SerialCfgParams", "PPPUDPProxyTransmitBuffSize", data->PPPUDPProxyTransmitBuffSize);

	IniSetUInt(ini, "SerialCfgParams", "PPPUDPProxyReceiveBuffSize", data->PPPUDPProxyReceiveBuffSize);

	IniSetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/0", data->PPPRemoteConsoleIPAdd[0]);
	IniSetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/1", data->PPPRemoteConsoleIPAdd[1]);
	IniSetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/2", data->PPPRemoteConsoleIPAdd[2]);
	IniSetUInt(ini, "SerialCfgParams", "PPPRemoteConsoleIPAdd/3", data->PPPRemoteConsoleIPAdd[3]);

	IniSetUInt(ini, "SerialCfgParams/BadPasswd", "GenEvent", data->BadPasswd.GenEvent);
	IniSetUInt(ini, "SerialCfgParams/BadPasswd", "ThreshNum", data->BadPasswd.ThreshNum);
	IniSetUInt(ini, "SerialCfgParams/BadPasswd", "ResetInterval", data->BadPasswd.ResetInterval);
	IniSetUInt(ini, "SerialCfgParams/BadPasswd", "LockoutInterval", data->BadPasswd.LockoutInterval);

	IniSaveFile(ini,File);
	if(g_corefeatures.dual_image_support != ENABLED)
	{
		IniCloseFile(ini);
		ini = NULL;
	}
	return 0;
}

